### ISSUE TITLE
[Node] context.log fails when given JSON

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#102]
# Error

```
2016-03-15T16:46:04 Function started
2016-03-15T16:46:05 Node.js HTTP trigger function processed a request. Name=https://functions8dbff8a7.azurewebsites.net/api/jshelloworld?code=pmgrtR/DU8fPYRurF2A3S9Q7hBHncT4bfhsUDG7J8/ZTuUYGAuUz5w==
2016-03-15T16:46:05 Error: Unable to cast object of type 'System.Dynamic.ExpandoObject' to type 'System.String'.
    at Error (native)
    at Object.log (<anonymous>:1:55)
    at module.exports (D:\home\site\wwwroot\jshelloworld\index.js:3:13)
    at eval (eval at <anonymous> (C:\Program Files (x86)\SiteExtensions\Functions\0.1.9\bin\edge\double_edge.js:34:28), <anonymous>:29:7)
2016-03-15T16:46:05 System.Exception: Error: Unable to cast object of type 'System.Dynamic.ExpandoObject' to type 'System.String'.
    at Error (native)
    at Object.log (<anonymous>:1:55)
    at module.exports (D:\home\site\wwwroot\jshelloworld\index.js:3:13)
    at eval (eval at <anonymous> (C:\Program Files (x86)\SiteExtensions\Functions\0.1.9\bin\edge\double_edge.js:34:28), <anonymous>:29:7)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.<Invoke>d__16.MoveNext()
2016-03-15T16:46:05 Function completed (Failure)
```

# Code

```
module.exports = function (context, req) {
    context.log('Node.js HTTP trigger function processed a request. Name=' + req.originalUrl);
    context.log(JSON.stringify(process.versions)); // THIS LINE HERE!!!!!

    if (typeof req.query.name == 'undefined') {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string!!!!!!!!!!"
        }
    }
    else {
        context.res = {
            status: 202, /* Defaults to 200 */
            body: {
                command: "hello",
                target: req.query.name
            } 
        }
    }
    context.done();
}
```

**Comment by davidebbo** [comment]
Does not repro for me. It correctly prints:

    2016-03-15T16:56:48 {"http_parser":"2.5.0","node":"4.1.1","v8":"4.5.103.33","uv":"1.7.4","zlib":"1.2.8","ares":"1.10.1-DEV","modules":"46","openssl":"1.0.2d"}

**Comment by christopheranderson** [comment]
Maybe this has been fixed? My host is old. If someone else has a no repro, I'll cycle my site and check again.

**Comment by davidebbo** [comment]
Oh, maybe you're still using that site where I had put a private host on it? If so, you're frozen with those bits. Try setting `WEBSITE_PRIVATE_EXTENSIONS=0` in the site's App Settings.

**Comment by mathewc** [comment]
No repro - I just tried on the latest bits.
