### ISSUE TITLE
Node.js functions start execution before modules have been installed

### ISSUE THREAD

**Issue by timfpark** [Azure/azure-webjobs-sdk-script#1050]
When using continuous integration to deploy an Azure Function written in node.js, when you include a package.json with a set of modules that need to be installed, function execution start before this 'npm install' completes.
 
#### Repro steps

Use the canonical event hub sample to repro ala http://github.com/timfpark/ah-eh-test with an Event Hub that has events in it that will immediately fire.

1. Set app setting AzureWebJobsEventHubReceiver to the connection string for this Event Hub.
2. Setup continous integration to deploy app from Github repo.

#### Expected behavior

Azure Functions installs modules before starting execution.

#### Actual behavior

Azure Function fails a number of times with "can't find module" errors until 'npm install' completes:

2016-12-13T18:32:05.462 Function started (Id=561f215f-4eb8-4510-9d64-5c45215677c0)
2016-12-13T18:32:05.772 Function completed (Failure, Id=d4f35507-c676-42d9-993d-2a7cdc10327e)
2016-12-13T18:32:05.788 Function completed (Failure, Id=d8df8c8d-9238-4589-a605-231fb5f106b3)
2016-12-13T18:32:05.804 A ScriptHost error has occurred
2016-12-13T18:32:05.804 Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\featureIntersection\intersect.js:3:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
2016-12-13T18:32:05.804 A ScriptHost error has occurred
2016-12-13T18:32:05.804 Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\featureIntersection\intersect.js:3:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
2016-12-13T18:32:05.823 Function completed (Failure, Id=d3000565-6478-49b7-a109-42a8d59be9f1)

#### Known workarounds

Problem eventually resolves itself when modules are installed.

**Comment by mathewc** [comment]
Thanks. Your repo link above doesn't resolve. Are you using your own custom deployment script to perform the NPM restore?
