### ISSUE TITLE
CLI: Update to WebJobs SDK release with improved error message for null connection string

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1069]

**Comment by ahmelsayed** [comment]
The latest SDK `Microsoft.Azure.WebJobs.2.0.0-beta2-10489` is still throwing the same nullref?

**Comment by lindydonna** [comment]
@soninaren Can you confirm that your fix is in `Microsoft.Azure.WebJobs.2.0.0-beta2-10489`?

**Comment by soninaren** [comment]
From what i can see in app veyor it is present in build 10509. I don't know how the artifacts are generated from there. The version number for nuget and build may not match

**Comment by ahmelsayed** [comment]
maybe it's just a matter of getting the latest build on myget. that probably doesn't happen automatically

**Comment by lindydonna** [comment]
@ahmelsayed No, but on email Mathew said he uploaded it manually.

**Comment by soninaren** [comment]
I decompiled the dll to check if my changes are there. Looks like they are present in the binary file. @ahmelsayed give me the repro steps.

**Comment by ahmelsayed** [comment]
I don't know how to give you a repro. I updated the refrenced package in `rename-cli` branch. 
Pull, build then run func.exe for a local function app folder that has a timer function for example and no storage account set. You'll get a nullref in `ScriptHostManager.cs:L161`
here is the stack
```
   at Microsoft.Azure.WebJobs.Host.Storage.StorageAccountExtensions.AssertTypeOneOf(IStorageAccount account, StorageAccountType[] types)
   at Microsoft.Azure.WebJobs.Host.SingletonManager.GetLockDirectory(String accountName)
   at Microsoft.Azure.WebJobs.Host.SingletonManager.<TryLockAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.<StartAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.<StartAsyncCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.<StartAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) in D:\\repos\\azure-webjobs-sdk-script2\\src\\WebJobs.Script\\Host\\ScriptHostManager.cs:line 123"
```

**Comment by lindydonna** [comment]
Moving to 0.10 milestone

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-cli#3
