### ISSUE TITLE
Occasional console related exception

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1076]
There appears to be some sort of race condition that can occur that results in the following exception and stack trace:

```
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at Colors.Net.ColoredConsoleWriter.Write(Object ovalue)
   at Colors.Net.ColoredConsoleWriter.WriteLine(Object value)
   at Colors.Net.ColoredConsole.WriteLine(Object value)
   at WebJobs.Script.Cli.Diagnostics.ConsoleTraceWriter.Trace(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Script.CompositeTraceWriter.Trace(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Script.CompositeTraceWriter.Trace(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.InvokeTraceWriters(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.Trace(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.LogFunctionStartedAsync(FunctionStartedMessage message, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.LogFunctionStartedAsync(FunctionStartedMessage message, IFunctionOutputDefinition functionOutput, IReadOnlyDictionary`2 parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__1a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__2.MoveNext()
```
I can't reliably reproduce it, but I only ever see it when there are multiple concurrent function executions. 

@ahmelsayed Perhaps the issue is that the ColoredConsoleWriter in Colors.Net is not thread safe?

**Comment by paulbatum** [comment]
See above. If this is indeed a colors issue you should be able to write a unit test that hammers the API on multiple threads and repros pretty easy.
