### ISSUE TITLE
BlobTrigger template out of box usability issues

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1091]
If you simply create a blob function from our default template and click Run, you'll be sad. You'll get a failure out of the box. @davidebbo found this.

This is because the test data used is a blob path that doesn't exist, which will cause the runtime invocation to fail. We should figure out a way to improve this - likely lots of users are running into this.

**Comment by christopheranderson** [comment]
@davidebbo will provide the current error message.

We need to improve the error message to know what the issue is

**Comment by davidebbo** [comment]
More info about scenario and current error handling.

- Create new Blob Trigger C# function, keeping everything default
- Click Run

In the Logs window, you get this:

    2017-01-09T19:03:42.802 Exception while executing function: Functions.BlobTriggerCSharp1. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'myBlob'. Microsoft.WindowsAzure.Storage: The remote server returned an error: (404) Not Found.

The real reason it's failing is that the blob `samples-workitems/workitem.txt` does not exist, but nothing in the error message leads to this.

Furthermore, if you got to the Monitor tab, you can more puzzling information:

```
Paremeter:
  myBlob: The remote server returned an error: (404) Not Found.
  name: Binding data does not contain expected value 'name'.
  Failure: One or more errors occurred.
```

And then a big chunk of meaningless (to the user) log:

```
...ebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Converters.CompositeAsyncObjectToTypeConverter`1.<TryConvertAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Blobs.Triggers.BlobTriggerBinding.<BindAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.<BindCoreAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---

```

**Comment by davidebbo** [comment]
In term of expected behavior, I'd want to see an error along the lines of:

    Failed to bind parameter myBlob because the blob samples-workitems/workitem.txt does not exist.

**Comment by MisinformedDNA** [comment]
Isn't the real problem simply the existence of the Run button? Clicking Run doesn't make a lot of sense with blob and queue triggers, at least how it's currently implemented. Assume the path is `samples-workitems/*.txt`, what blob do you expect it to access? The first one? And what if it finds none? Should it really give you an error? Or a message that says "No files match the pattern `samples-workitems/*.txt`.

We are telling the Run button to do something when it is not in the correct state because there is no guarantee there is data to process. Though you would never expect to be in this state in normal operation, because a BlobTrigger event tells us exactly what blob and that the blob actually exists.

Instead of improving the error message (or in addition to), I think the Run button needs some more work. For instance, I would suggest for BlobTriggers, the Run button have a required parameter, which would allow the user to choose which file in blob storage they want to execute on.

Similarly, for queue triggers, I would want to specify the message, not assume/hope that something is in the queue.

**Comment by mathewc** [comment]
@MisinformedDNA In all of these run cases, the function is only operating on data passed from the portal UI. E.g. in your queue example, it won't be checking the queue for anything - the data in the "Request body" input box under the "Test" pane is what is used. For blobs, the input box is used to specify a blob path to trigger on. So for these Run scenarios, the intent is that you configure this input value to point to a valid test blob.

**Comment by MisinformedDNA** [comment]
Ha! I always associated that pane as for HttpTriggers because of the term "Request body".

I'll add further comments on the new issue.

**Comment by singhalsunil065** [comment]
how can i trigger an Azure Function locally on Blob Trigger w/o hooking up to an actual Storage Account?

Steps to reproduce:
1) Create an Azure Function based on Storage Blob Trigger. change nothing
2) Run by ctrl+F5 or just F5 using VS2019
3) Create a folder samples-workitems under bin (default folder where compile o/p goes) and add test.txt file
4) Send a request over http: http://localhost:7071/admin/functions/Function1
with body:
{
    "input": "samples-workitems/test.txt"
}

It errors out saying that 

System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: One or more errors occurred. (Exception binding parameter 'myBlob') (Exception binding parameter 'name'). Exception binding parameter 'myBlob'. Microsoft.WindowsAzure.Storage: The specified container does not exist.

What am i missing?

**Comment by MisinformedDNA** [comment]
@singhalsunil065 I could be wrong, but I think the original issue was in relation to the portal UI.

But you should download [Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/), which comes with an emulator, and then you can add your data that way.
