### ISSUE TITLE
Azure Functions CLI Throws Exception when selecting the stack in Cmd.exe

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-webjobs-sdk-script#1101]
#### Repro steps

Home Dev Machine
Windows 10 Home 14393.576

npm --version
3.10.9
node --version
v6.9.4
Azure Functions Cli (1.0.0-beta.9)
This only occurs when the Screen Buffer Height is set to 300 for cmd.exe.
It was resolved by increasing the screen buffer Height.

Provide the steps required to reproduce the problem

1.  Run Func New

2. Press the Down cursor to select a stack

#### Expected behavior

The Stack would be selected and the type of function would be displayed.

#### Actual behavior

An exception is thrown 

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's b
uffer size in that dimension.
Parameter name: top
Actual value was 300.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at WebJobs.Script.Cli.Actions.LocalActions.CreateFunctionAction.DisplaySelectionWizard[T](IEnumerable`1 option
s)
   at WebJobs.Script.Cli.Actions.LocalActions.CreateFunctionAction.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebJobs.Script.Cli.ConsoleApp.<RunAsync>d__4`1.MoveNext()

#### Known workarounds
Set the Screen Buffer Height to 800.

**Comment by ahmelsayed** [comment]
Thanks Finbar. Btw, we have a new repo just for the cli here https://github.com/Azure/azure-functions-cli
