### ISSUE TITLE
Blob Trigger never firing after long period of inactivity

### ISSUE THREAD

**Issue by martinabbott** [Azure/azure-webjobs-sdk-script#1103]
This has been raised as a different issue to [Function not triggered by blob](https://github.com/Azure/azure-webjobs-sdk-script/issues/691) after speaking to @davidebbo 

The issue is that after a long period of inactivity the Blob trigger does not fire at all, even with the Function App blade opened (which is the original issue 691)

I have created a Timer Trigger in an attempt to keep the Function App alive and the monitor shows all the executions, this has worked as a workaround to 691 in another Function App.

I can create a new Blob Trigger against the same blob folder (called New...) as the one that fails and that works.

When manually running the failing Blob Trigger, it throws an exception:

-------
  myBlob  The remote server returned an error: (404) Not Found.  
 log    
 _context  304a7c8b-91ae-48a8-a59e-51f67614bf2b  
  Failure  Exception binding parameter 'myBlob'  
-------

The stack trace in the Monitor window is:

-------
...mpilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Converters.CompositeAsyncObjectToTypeConverter`1.<TryConvertAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Blobs.Triggers.BlobTriggerBinding.<BindAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.<BindCoreAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
------

As this is impacting a customer, I will need to delete and recreate this to ensure my customer can move forward so diagnosis opportunity is very time limited.

The Function App information has been sent in an email to @davidebbo to help diagnosis.

**Comment by davidebbo** [comment]
Can you check whether that function has the disabled flag in its function.json? Based on the logs I see, the runtime appears to treat it as disabled.

**Comment by davidebbo** [comment]
Note that even if disabled, you should be able to run it manually. But this to work, you need to pass a valid blob path in the request body, e.g. if you pass samples-workitems/foo.json, the blob needs to exist.

**Comment by martinabbott** [comment]
Yeah so updating the test works, picks up the file no problem, sorry just rushing and missed the process.

Yes it is set to disabled, which is a puzzle as I wouldn't have touched that...

I've set to Enabled and tested with an actual file and that works.

Puzzled as to how (and why) it would've gotten set to disabled.

**Comment by davidebbo** [comment]
Note that setting it to disabled is common when developing, to avoid having it drain everything from the container before the function is ready.

Anyway, closing this, but I do think we need to improve the error handling here (I'll track separately).

**Comment by martinabbott** [comment]
Okay thanks, this is a prod system so shouldn't have been disabled.

Thanks for the quick follow up.
