### ISSUE TITLE
functions runtime slow to start after change deteceted

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#1163]
After making a change to a file, the functions runtime is slow to restart.

#### Repro steps

Provide the steps required to reproduce the problem

1. Install the functions runtime as part of an Azure Web App

2. Make a change to a file

#### Expected behavior

I'd expect that the runtime would go from starting to running relatively quickly.

#### Actual behavior

It's sometimes absurdly slow (15-20min),  even when changing a single file.

#### Related information 

I'm running functions written in Node on Functions 1.0.10690. I see this issue mainly if I need to debug and make a quick change through FTP. When I deploy using my CI server, which uses Web Deploy, this seems to happen less often.

I also tend to see this error in my logs during this change from starting to pending:

```
Failed to copy job files: System.Threading.ThreadAbortException: Thread was being aborted.
   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry)
   at Kudu.Core.Jobs.BaseJobRunner.CacheJobBinaries(JobBase job, IJobLogger logger)
```

**Comment by jamesdixon** [comment]
Here's some log output that helps with a timeline:

```
[01/30/2017 21:09:58 > decc34: SYS INFO] Job directory change detected: Job file 'ProcessInvoices\lib\scout_fees.js' timestamp differs between source and working directories.
[01/30/2017 21:14:23 > decc34: SYS INFO] WebJob is stopping due to website shutting down
[01/30/2017 21:14:23 > decc34: SYS INFO] Status changed to Stopping
[01/30/2017 21:14:29 > decc34: SYS INFO] Status changed to Stopped
[01/30/2017 21:14:29 > decc34: SYS ERR ] Failed to copy job files: System.Threading.ThreadAbortException: Thread was being aborted.
   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry)
   at Kudu.Core.Jobs.BaseJobRunner.CacheJobBinaries(JobBase job, IJobLogger logger)
[01/30/2017 21:14:51 > decc34: SYS INFO] Status changed to Starting
[01/30/2017 21:14:51 > decc34: SYS INFO] WebJob singleton setting is False
[01/30/2017 21:31:54 > decc34: SYS INFO] WebJob is stopping due to website shutting down
[01/30/2017 21:31:54 > decc34: SYS INFO] Status changed to Stopping
[01/30/2017 21:31:59 > decc34: SYS ERR ] Failed to copy job files: System.Threading.ThreadAbortException: Thread was being aborted.
   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry)
   at Kudu.Core.Jobs.BaseJobRunner.CacheJobBinaries(JobBase job, IJobLogger logger)
[01/30/2017 21:31:59 > decc34: SYS INFO] Status changed to Stopped
[01/30/2017 21:33:08 > decc34: SYS INFO] Status changed to Starting
[01/30/2017 21:33:08 > decc34: SYS INFO] WebJob singleton setting is False
[01/30/2017 21:38:45 > decc34: SYS INFO] Run script 'run.cmd' with script host - 'WindowsScriptHost'
[01/30/2017 21:38:45 > decc34: SYS INFO] Status changed to Running
[01/30/2017 21:38:46 > decc34: INFO] 
[01/30/2017 21:38:46 > decc34: INFO] D:\local\Temp\jobs\continuous\scripthost\d5tueeos.g0h>.\bin\Microsoft.Azure.WebJobs.Script.Host.exe
```

Note, I did restart my app service instance two times during this period to see if it helped, but ultimately, it resulted in waiting almost 30 minutes before it had restarted.

**Comment by jamesdixon** [comment]
Anyone have any idea on this? This is becoming a big problem when needing to make quick fixes via FTP. Thanks!

**Comment by mathewc** [comment]
Can you share the details of how these files are deployed? I assume you've deployed as a continuous webjob as described [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki#option-2-no-http-functionwebhook-support).

If so, then this is just a normal continuous webjob setup, and the Kudu webjob infrastructure is responsible for the restart behavior. I.e., this might be a Kudu bug. @davidebbo

**Comment by jamesdixon** [comment]
@mathewc thanks for the reply.

Yes, the runtime is deployed as a continuous webjob.

As for file changes, as mentioned above, when I deploy changes through my CI, which uses Web Deploy, it seems the restarts take effect relatively quickly as expected. However, if I need to make a quick change via FTP, this is where the problems start. The change is detected and then there's a significant delay before the runtime is "running." Restarts and stops of the actual app service instance do not seem to remedy the issue.

**Comment by jamesdixon** [comment]
Contents of `run.cmd`:

```
.\bin\Microsoft.Azure.WebJobs.Script.Host.exe
```

**Comment by mathewc** [comment]
That looks good. What happens if rather than FTP, you modify files in the Kudu Console directly? When I do that, I see changes take effect immediately. What does your directory structure look like, and what file are you modifying? One of the primary script files, or a file in a shared directory?

**Comment by jamesdixon** [comment]
Here's my first test:

I changed one of my webjob files (located at `app_data/jobs/continuous/scripthost/EmailNotifications`) directly through Kudu and it's been over 20 minutes and still has not restarted. Here's the logs as of now:

```
[02/02/2017 20:08:34 > decc34: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[02/02/2017 20:08:34 > decc34: SYS INFO] Status changed to Stopping
[02/02/2017 20:08:39 > decc34: ERR ] Thread was being aborted.
[02/02/2017 20:08:39 > decc34: SYS INFO] WebJob process was aborted
[02/02/2017 20:08:41 > decc34: SYS INFO] Status changed to Stopped
[02/02/2017 20:08:41 > decc34: SYS INFO] Status changed to Starting
[02/02/2017 20:10:35 > decc34: SYS INFO] Job directory change detected: Job file 'EmailNotifications\index.js' timestamp differs between source and working directories.`
```

Once it's running, I'll try editing a file in my main application (outside of the webjob directory).

**Comment by jamesdixon** [comment]
The above restart finished at `20:28`.

I tried editing an application outside of my webjob directory and as expected, it took hold immediately and did not affect the status of the webjob itself.

**Comment by mathewc** [comment]
I tried myself in my app, a Node.js function app deployed the same way, and my restart is immediate:

```
[02/02/2017 22:47:34 > 2fba61: INFO] Executing 'Functions.QueueTrigger' (Reason='New queue message detected on 'testqueue'.', Id=b8051038-3b27-4bb5-a1a3-d649769dda28)
[02/02/2017 22:47:34 > 2fba61: INFO] Function started (Id=b8051038-3b27-4bb5-a1a3-d649769dda28)
[02/02/2017 22:47:35 > 2fba61: INFO] Node.js queue trigger function processed work item hello
[02/02/2017 22:47:35 > 2fba61: INFO] Function completed (Success, Id=b8051038-3b27-4bb5-a1a3-d649769dda28)
[02/02/2017 22:47:36 > 2fba61: INFO] Executed 'Functions.QueueTrigger' (Succeeded, Id=b8051038-3b27-4bb5-a1a3-d649769dda28)
[02/02/2017 22:48:17 > 2fba61: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[02/02/2017 22:48:17 > 2fba61: SYS INFO] Status changed to Stopping
[02/02/2017 22:48:22 > 2fba61: ERR ] Thread was being aborted.
[02/02/2017 22:48:22 > 2fba61: SYS INFO] WebJob process was aborted
[02/02/2017 22:48:22 > 2fba61: SYS INFO] Status changed to Stopped
[02/02/2017 22:48:22 > 2fba61: SYS INFO] Status changed to Starting
[02/02/2017 22:48:22 > 2fba61: SYS INFO] Job directory change detected: Job file 'QueueTrigger\index.js' timestamp differs between source and working directories.
[02/02/2017 22:48:23 > 2fba61: SYS INFO] Run script 'run.cmd' with script host - 'WindowsScriptHost'
[02/02/2017 22:48:23 > 2fba61: SYS INFO] Status changed to Running
[02/02/2017 22:48:23 > 2fba61: INFO] 
[02/02/2017 22:48:23 > 2fba61: INFO] D:\local\Temp\jobs\continuous\ScriptHost\ktrpfptr.1tc>.\bin\Microsoft.Azure.WebJobs.Script.Host.exe
[02/02/2017 22:48:25 > 2fba61: INFO] Reading host configuration file 'D:\local\Temp\jobs\continuous\ScriptHost\ktrpfptr.1tc\host.json'
[02/02/2017 22:48:25 > 2fba61: INFO] Host lock lease acquired by instance ID '2fba610d64ec93e4f41990a0526862aa'.
[02/02/2017 22:48:25 > 2fba61: INFO] Generating 1 job function(s)
[02/02/2017 22:48:25 > 2fba61: INFO] Starting Host (HostId=6b919861cab44e68bfed5d2c2fe7fc0c, Version=1.0.10717.0, ProcessId=10612, Debug=False)
[02/02/2017 22:48:27 > 2fba61: INFO] Found the following functions:
[02/02/2017 22:48:27 > 2fba61: INFO] Host.Functions.QueueTrigger
[02/02/2017 22:48:27 > 2fba61: INFO] Job host started
```

**Comment by mathewc** [comment]
Can you try something - create a **settings.job** file right next to your run.cmd file, containing the following contents:

```javascript
{
  "is_in_place": true
}
```

This tells the Kudu jobs infrastructure to not shadow copy the job files. The theory is that you have a very large NPM tree, and the shadow copying is what is slow.

**Comment by jamesdixon** [comment]
@mathewc that appears to have worked perfectly! My jobs do have a number of NPM dependencies, so that would explain things.

I appreciate your help!

Cheers.

**Comment by mathewc** [comment]
I'll update the install step wiki with a note about this as well.
