### ISSUE TITLE
CLI: System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by amragaey** [Azure/azure-webjobs-sdk-script#1174]
I installed azure-functions-cli package, and I'm trying to create a new function but getting an exception instead. 
This exception occurs in Git Bash, but it's working fine with PowerShell.

> $ func function create

```
Select a language: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_CursorLeft()
   at WebJobs.Script.Cli.Actions.LocalActions.CreateFunctionAction.DisplaySelect       ionWizard[T](IEnumerable`1 options)
   at WebJobs.Script.Cli.Actions.LocalActions.CreateFunctionAction.<RunAsync>d__       2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot       ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebJobs.Script.Cli.ConsoleApp.<RunAsync>d__4`1.MoveNext()```

**Comment by mathewc** [comment]
CLI is in its own repo now. This issue should be moved there: https://github.com/Azure/azure-functions-cli/issues

**Comment by amragaey** [comment]
Thanks for advice, I got here by an old link in the npm page here: https://www.npmjs.com/package/azure-functions-cli. Please fix the link to refer to the CLI repo.

**Comment by mathewc** [comment]
Yep, we've got an issue to fix the npm link, thanks.
