### ISSUE TITLE
CLI: HTTP 400 error reported when trying to create a function app on azure

### ISSUE THREAD

**Issue by iain-peddie-tessella** [Azure/azure-webjobs-sdk-script#1175]
Please provide a succinct description of the issue.

#### Repro steps

I have a resource group for which I am an owner; I am also a co-admin on the subscription the resource group is in. I have installed the functions-cli.

I am now calling the following commands from a bash shell on my local machine:

func azure login
func azure account set $sub
func azure functionapp create --resource-group $rg --name $app_name --subscription $sub --plan $plan_id --location $location

I have set variables up correctly as far as I can tell. These variables are:
$rg : contains the resource group name
$sub: contains the relevant subscritpion - my account has access to both
$app_name : contains the name of the function app that I want to create
$plan_id : contans the name of a created app service plan in the same resource group.

The commands fail at the third step.

#### Expected behavior

Provide a description of the expected behavior.
I expect the function app  compoment to be created, or failing that an error message that explains why something has failed so that I can fix the issue if the input is incorrect. For example:  "Error: you have used an app service plan ID , but we need the app service name". 

#### Actual behavior
I get an error message that doesn't help me understand what has gone wrong:

```System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WebJobs.Script.Cli.Arm.ArmManager.<CreateFunctionsStorageAccountAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Arm.ArmManager.<EnsureAStorageAccountAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Arm.ArmManager.<CreateFunctionAppAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Actions.AzureActions.CreateFunctionAppAction.<RunAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```
Provide a description of the actual behavior observed. 

#### Known workarounds

Creating the app via the portal works - but I want to be able to script the deployments. 

#### Related information 

I have been creating this using bash scripting using git-bash on a windows 10 development machine. I have used a similar approach with Azure CLI 2 to create a storage account and a app service plan.

I am running version 1.0.0-beta.9

**Comment by mamaso** [comment]
Can you try running fiddler to get a trace of the http response that's failing?

**Comment by mathewc** [comment]
CLI is in its own repo now. This issue should be moved there: https://github.com/Azure/azure-functions-cli/issues

**Comment by iain-peddie-tessella** [comment]
Ok, fair enough, I'll repost, but I posted here because of the instruction at the bottom of the instruction of how to file bugs on the [npmjs page for azure-functions-cli](url)
https://www.npmjs.com/package/azure-functions-cli

So, if this is no longer the place for these bugs, it would be helpful to have the documentation updated to save everyone some time.

**Comment by mathewc** [comment]
Thanis @iain-peddie-tessella. I've logged https://github.com/Azure/azure-functions-cli/issues/56 for us to fix the npm instructions, thanks for pointing that out. I've also moved this bug to that repo https://github.com/Azure/azure-functions-cli/issues/57.
