### ISSUE TITLE
Script host crash loop with access denied to debug_sentinel

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#1212]
the host can enter a crash loop with this exception 

```
System.UnauthorizedAccessException: Access to the path 'D:\home\LogFiles\Application\Functions\Host\debug_sentinel' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalGetLastWriteTimeUtc(String path, Boolean checkHost)
   at System.IO.File.GetLastWriteTime(String path)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize()
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(ScriptSettingsManager settingsManager, ScriptHostConfiguration scriptConfig)
   at Microsoft.Azure.WebJobs.Script.ScriptHostFactory.Create(ScriptSettingsManager settingsManager, ScriptHostConfiguration config)
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken)
```

**Comment by mathewc** [comment]
We need to figure out how these files were made read only. We make a lot of assumptions (both in these log directories) as well as in other directories like the data directory (keys, etc.) that we can write to files. If someone makes them read only that breaks things.

**Comment by fabiocav** [comment]
There is some investigation happening now as this could be caused by App Service infrastructure components or Azure Files.

The key issue, though, is that errors like this left the runtime APIs in a bad state, returning a 500 when they could be providing detailed information about what was happening to be surfaced by the portal.

**Comment by lindydonna** [comment]
This is being investigated by Jaro to see what's going on.
