### ISSUE TITLE
crash loop due to missing connection string 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#1251]
call stack 

```
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.QueueTriggerCSharp1' ---> System.InvalidOperationException: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobsEndpoint=<REDACTED>' is missing or empty.
   at Microsoft.Azure.WebJobs.ServiceBus.MessagingProvider.GetConnectionString(String connectionStringName)
   at Microsoft.Azure.WebJobs.ServiceBus.MessagingProvider.CreateMessagingFactory(String entityPath, String connectionStringName)
   at Microsoft.Azure.WebJobs.ServiceBus.Triggers.ServiceBusTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.<TryCreateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsyncCore>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__9.MoveNext()
```

**Comment by davidebbo** [comment]
Related to #1250

**Comment by mathewc** [comment]
This will be addressed by @mamaso https://github.com/Azure/azure-webjobs-sdk/pull/1035
