### ISSUE TITLE
Unable to reliabily pass in a CloudQueueMessage into my function.

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-webjobs-sdk-script#1366]
I wanted to pass in a CloudQueueMessage into my function so my queue job could update it / use all the defined meta data without me having to declare extra parameters as well as (then I lose the body since I can only specify the body or the message id and pop receipt......)

However, it seemed completely random, but either all the time or part of the time I'd get the following exception when trying to use it in my function:

```
Exception while executing function: Functions.EventPost
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.EventPost ---> System.InvalidOperationException : Exception binding parameter 'message' ---> System.ArgumentNullException : String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage.get_AsBytes() at c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Queue\CloudQueueMessage.Common.cs : 146
   at Microsoft.Azure.WebJobs.Host.PropertyHelper.CallPropertyGetter[TDeclaringType,TValue](Func`2 getter,Object this)
   at Microsoft.Azure.WebJobs.Host.PropertyHelper.GetValue(Object instance)
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingDataProvider.GetBindingData(Object value)
   at Microsoft.Azure.WebJobs.Host.Queues.Triggers.UserTypeArgumentBindingProvider.UserTypeArgumentBinding.BindAsync(IStorageQueueMessage value,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Queues.Triggers.QueueTriggerBinding.BindAsync(Object value,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,IReadOnlyDictionary`2 parameters,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```

Here is the commit where I changed from cloud queue message into multiple parameters :( 

https://github.com/exceptionless/Exceptionless/commit/ddccc2876a9849e94db46f0b7559d7fe4b22af53

**Comment by christopheranderson** [comment]
@niemyjski - could you provide an example "poison" message?

**Comment by paulbatum** [comment]
Closing due to inactivity. Reopen if you have some repro steps for us!
