### ISSUE TITLE
int64 overflow in MetricsEventManager

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1376]
I came across the following stack trace in my App Insights exceptions view. If I had to guess, I'd say that it was probably from this line:

https://github.com/Azure/azure-webjobs-sdk-script/blob/d9feee3db2a59421fd5e11a0ac0636ca0a58049e/src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs#L462

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.Splitter ---> System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Decimal.ToUInt64(Decimal d)
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.MetricsEventManager.FunctionActivityTracker.<>c.<RaiseMetricsPerFunctionEvent>b__23_1(IGrouping`2 FunctionGroups)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.MetricsEventManager.FunctionActivityTracker.RaiseMetricsPerFunctionEvent()
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.MetricsEventManager.FunctionCompleted(FunctionStartedEvent completedEvent)
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.WebHostMetricsLogger.EndEvent(MetricEvent metricEvent)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.<Invoke>d__30.MoveNext()

```

**Comment by christopheranderson** [comment]
This could have been a negative number due weird time comparison quirks.
