### ISSUE TITLE
Sporadic issue restoring F# packages 

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#1504]
We have a customer that, upon package load, occassionally gets this error in one of his functions:

```
2017-05-10T14:16:12.594 Script for function 'my-function' changed. Reloading.
2017-05-10T14:16:21.080 Package restore failed:
2017-05-10T14:16:21.534 System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Script.Description.FSharpCompilation.GetEntryPointSignature(IFunctionEntryPointResolver entryPointResolver)
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.ReloadScriptAsync()
   at async Microsoft.Azure.WebJobs.Script.FuncExtensions.<>c__DisplayClass0_0`1.<Debounce>b__0[T](??)
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.RestorePackagesAsync(Boolean reloadScriptOnSuccess)
```

The HttpTrigger returns a 404 whenever this happens. This doesn't happen every time -- when it loads correctly, everything runs fine.

**Comment by fabiocav** [comment]
Did you have a basic repro? Details on packages being loaded?

**Comment by paulbatum** [comment]
@brettsam you have a repro?

**Comment by brettsam** [comment]
There's a pretty lengthy CRI mail with all of the details -- I've resent it several times and this issue is mentioned in it.
