### ISSUE TITLE
The formatter threw an exception while trying to deserialize the message

### ISSUE THREAD

**Issue by tmtso** [Azure/azure-webjobs-sdk-script#1636]
Hi, 
I've got a problem regarding my Azure Function which is connected to our Dynamics 365/CRM 2016 8.1.
Everytime I try to use the [SetStateRequest](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.setstaterequest.aspx) from the SDK, I get following error. But only when I run the function online, i debug-mode the is no error.....

> 2017-06-28T14:42:05.058 The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:ExecuteResult. The InnerException message was 'Error in line 1 position 1185. Element 'http://schemas.microsoft.com/xrm/2011/Contracts/Services:ExecuteResult' contains data from a type that maps to the name 'http://schemas.microsoft.com/crm/2011/Contracts:SetStateResponse'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'SetStateResponse' and namespace 'http://schemas.microsoft.com/crm/2011/Contracts'.'.  Please see InnerException for more details.
2017-06-28T14:42:05.183 System.Runtime.Serialization.SerializationException: Error in line 1 position 1185. Element 'http://schemas.microsoft.com/xrm/2011/Contracts/Services:ExecuteResult' contains data from a type that maps to the name 'http://schemas.microsoft.com/crm/2011/Contracts:SetStateResponse'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'SetStateResponse' and namespace 'http://schemas.microsoft.com/crm/2011/Contracts'.
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.PartInfo.ReadObject(XmlDictionaryReader reader, XmlObjectSerializer serializer)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.DeserializeParameterPart(XmlDictionaryReader reader, PartInfo part, Boolean isRequest)

My project.json contains the following values:

>{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.CrmSdk.CoreAssemblies": "8.2.0.2",
        "Microsoft.CrmSdk.Deployment": "8.2.0.2",
        "Microsoft.CrmSdk.Workflow": "8.2.0.2",
        "Microsoft.CrmSdk.XrmTooling.CoreAssembly": "8.2.0.5",
        "Microsoft.IdentityModel": "6.1.7600.16394",
        "Microsoft.IdentityModel.Clients.ActiveDirectory": "2.22.302111727"
      }
    }
  }
}

The other strange behavior is, that my try/catch (inside my custom dll) around the SetStateRequest is completely ignored.

>try
                {
                    SetStateRequest setStateRequest = new SetStateRequest()
                    {
                        EntityMoniker = new EntityReference
                        {
                            Id = leadMaster.Id,
                            LogicalName = leadMaster.LogicalName
                        },
                        State = new OptionSetValue(state.Value),
                        Status = new OptionSetValue(status.Value)
                    };
                    SetStateResponse response = (SetStateResponse)_service.Execute(setStateRequest);
                }
                catch (Exception)
                {   }

#### Investigative information

Please provide the following:

- Timestamp: 2017-06-28T14:42:01.144 
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: a825c95f-0014-4ac4-b046-49c0e0f9b54e
- Region: West Europe

As soon as I have more time, I will make a better example without any other calls (only the SetStateRequest)

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by Sheel7** [comment]
I am also receiving this error message. Did you ever find a resolution?
