### ISSUE TITLE
ArgumentException: Object of type 'ExecutionContext' cannot be converted to type 'TraceWriter'.

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-webjobs-sdk-script#1705]
I'm writing a simple function which uses the Durable Task extension, currently in alpha mode. When I try to trigger a simple orchestrator function, it fails with the following error message:

```
2017-07-25T16:56:25.697 Executing 'Functions.DurableTimer' (Reason='', Id=0b882ad6-f2ef-437b-8ba1-56101fcb8684)
2017-07-25T16:56:25.697 A ScriptHost error has occurred
2017-07-25T16:56:25.697 System.InvalidOperationException : [DF] cd9d14ad34c34ac6b8fc86b67ba0b5b9: Function 'DurableTimer', version '' failed with an error. Reason: System.ArgumentException: Object of type 'Microsoft.Azure.WebJobs.ExecutionContext' cannot be converted to type 'Microsoft.Azure.WebJobs.Host.TraceWriter'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.<InvokeCore>d__26.MoveNext() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs:line 268
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.<Invoke>d__32.MoveNext() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.<Execute>d__7.MoveNext(). IsReplay: False.
2017-07-25T16:56:25.697 Function started (Id=0b882ad6-f2ef-437b-8ba1-56101fcb8684)
2017-07-25T16:56:25.697 Function completed (Failure, Id=0b882ad6-f2ef-437b-8ba1-56101fcb8684, Duration=0ms)

```

Here is the function code:

```csharp
#r "Microsoft.Azure.WebJobs.Extensions.DurableTask"

using System;
using System.Threading;

public static async Task Run(DurableOrchestrationContext ctx, TraceWriter log)
{
    log.Info($"Durable function executed at: {ctx.CurrentUtcDateTime}");

    // sleep for one hour between calls
    DateTime nextExecution = ctx.CurrentUtcDateTime.AddHours(1);
    await ctx.CreateTimer(nextExecution, CancellationToken.None);

    int counterState = ctx.GetInput<int>();
    log.Info($"Counter state: {counterState}");

    counterState++;

    if (counterState < 5)
    {
        ctx.ContinueAsNew(counterState);
    } 
}
```

The issue happens whenever I have the `TraceWriter log` parameter in my function signature. The problem goes away when it is removed.

The name of the function app is **dftemp** and it runs in the Consumption plan in **West US 2**.

**Comment by cgillum** [comment]
It was brought up in another thread that the Durable Task extension may be using cached trigger objects, and I suspect that could result in problems like this. Closing for now until I can confirm.
