### ISSUE TITLE
Imperative binding(Binder) for servicebus queue failed with new release

### ISSUE THREAD

**Issue by utkarsh24** [Azure/azure-webjobs-sdk-script#1774]
We have a timer trigger function with singature :

**public static async Task Run(TimerInfo myTimer, TraceWriter log, CancellationToken cancellationToken, Binder binder)**

which was working fine until latest azure function release(Functions 1.0.11075) 

after new update we are getting error :
-----------------------------------------------------------------
No binding found for attribute 'Microsoft.Azure.WebJobs.ServiceBusAttribute'., Stack Trace:    at Microsoft.Azure.WebJobs.Binder.<BindAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Binder.<BindAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FunctionClassLibrary.AudienceCountUpdateTimerTrigger.<GetQueueBinder>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FunctionClassLibrary.AudienceCountUpdateTimerTrigger.<Run>d__1.MoveNext(), Source: Microsoft.Azure.WebJobs.Host, Inner Exception:
2017-08-11T07:36:54.363 Function completed (Success, Id=e99b49a1-29a7-48ed-9d47-00189ba570d4, Duration=10018ms)

------------------------------------------------------------------------------------

So, currently I have rolled back to older release(Functions 1.0.11027) by updating application settings key **FUNCTION_EXTENTION_VERSION** to **1.0.11027** from **~1** and it is working fine now

Please look in the issue ASAP as I have several function apps on dev and production environment and I don't want to change appsettings of all function app

**NOTE : I am using precompiled functions**

**Comment by utkarsh24** [comment]
Any updates....
Is anybody looking into this..??

**Comment by christopheranderson** [comment]
There is a patch that is out worldwide. Please switch to ~1 and look to see that the version is 1.0.11090.

Please reopen if this doesn't fix it.
