### ISSUE TITLE
NotificationHub name property (hubName) in binding cannot be mapped to app setting.

### ISSUE THREAD

**Issue by Jonlondon** [Azure/azure-webjobs-sdk-script#1907]
Hello everyone,

My issue is quite simple. I want to bind a notificationhub name (hubName property) to an app setting in my azure function but it fails.

#### Investigative information

- Timestamp: 9/14/2017 3:05:01 PM
- Function name: SendNotification
- Invocation ID: 0d1b7458-ff00-415f-b100-47faa805a654_G4
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

Here is my issue. I want to bind a notificationhub name to an app setting in my azure function.
Here is the binding
{
 "type": "notificationHub",
 "name": "notification",
 "tagExpression": "{peopleKey}", 
 "hubName": "%NotificationHubName%",
 "connection": "NotificationHubConnection",
 "enableTestSend": true,
 "direction": "out"
}
The problem is %NotificationHubName% is never replaced by the app setting I set and I then cannot connect to my notification hub.
Of course it works if I write the static name of the notificationhub instead.

#### Expected behavior

%NotificationHubName% must be replaced by the app setting value to be able to connect to notificationhub (works for other bindings or triggers).

#### Actual behavior

Exception while executing function: Functions.SendNotification
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.SendNotification ---> Microsoft.Azure.NotificationHubs.Messaging.MessagingEntityNotFoundException : The remote server returned an error: (404) Not Found. No service is hosted at the specified address..TrackingId:0d1b7458-ff00-415f-b100-47faa805a654_G4,TimeStamp:9/14/2017 3:05:01 PM ---> System.Net.WebException : The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.Azure.NotificationHubs.NotificationRequestAsyncResult`1.<>c.<GetAsyncSteps>b__26_3(TAsyncResult thisPtr,IAsyncResult r)
   at Microsoft.Azure.NotificationHubs.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result) 
   End of inner exception
   at Microsoft.Azure.NotificationHubs.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.NotificationHubs.NotificationHubManager.EndSendNotification(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,Func`2 endFunction,Action`1 endAction,Task`1 promise,Boolean requiresSynchronization)
   at async Microsoft.Azure.WebJobs.Extensions.NotificationHubs.NotificationHubAsyncCollector.AddAsync(Notification item,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.BindAsyncCollectorAsync[T](BindingContext context) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Binding\FunctionBinding.cs : 203
   at async Microsoft.Azure.WebJobs.Script.Binding.ExtensionBinding.BindAsync(BindingContext context) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Binding\ExtensionBinding.cs : 59
   at async Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.ProcessOutputBindingsAsync(Collection`1 outputBindings,Object input,B…

#### Known workarounds

Enter the name of the hubName without using app settings.

#### Related information 

* Programming language used : Javascript

**Comment by christopheranderson** [comment]
@paulbatum - low hanging fruit

**Comment by alrod** [comment]
Fixed.

**Comment by fabiocav** [comment]
@alrod , can you please link the PR/commit?
