### ISSUE TITLE
Investigate function app throwing repeated OperationCanceledException

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1955]
We have a case of a JavaScript function app with service bus triggers getting into a state where it repeatedly throws errors with the following stack trace:
```
System.OperationCanceledException : The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async Microsoft.Azure.WebJobs.ServiceBus.Triggers.BrokeredMessageToStringConverter.ConvertAsync(BrokeredMessage input,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.ServiceBus.Triggers.ConverterArgumentBindingProvider`1.ConverterArgumentBinding.BindAsync[T](BrokeredMessage value,ValueBindingContext context)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.ServiceBus.Triggers.ServiceBusTriggerBinding.BindAsync(Object value,ValueBindingContext context)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindAsync[TTriggerValue](??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.BindAsync(IBindingSource bindingSource,ValueBindingContext context)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)
```

The error count can be as high as 100K on a single VM over the course of several days.

Lookup details for one example:
```
Function started (Id=06d9d6dd-3db0-49c5-9437-c06c8287ae88) 
2017-09-22 20:33:08.4075334
West US
```

**Comment by paulbatum** [comment]
Resolved by https://github.com/Azure/azure-webjobs-sdk-script/pull/2058
