### ISSUE TITLE
We are not able to retrieve the runtime master key. Please try again later.

### ISSUE THREAD

**Issue by guybartal** [Azure/azure-webjobs-sdk-script#2082]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: serverless-demo-ebc-vs-fix
- Function name(s) (as appropriate): ResizeImage, AddNewImageToDb, DescribeImage, FaceRecognition
- Invocation ID: n/a, it fails on application start
- Region: west-central-us

two kinds of errors:
1)
![snip_20171031180753](https://user-images.githubusercontent.com/3179107/32234838-79889d02-be66-11e7-8186-a869d7217e39.png)
2)
Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: 58ccb57c3f6a4811bb5ae05180ab48da

Timestamp: 2017-10-31T16:05:25.976Z

https://github.com/AzureIsrael/serverless-demo-vs.git
when I run it locally it works perfectly.

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by guybartal** [comment]
I've noticed that all my functions now throws this kind of exception:
I think it happened after updating function SDK tooling today and publish to Azure. so maybe it related...

Exception while executing function: AddNewImageToDB
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: AddNewImageToDB ---> System.InvalidOperationException : Exception binding parameter 'document' ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at Microsoft.Azure.Documents.Client.DocumentClient.Initialize(Uri serviceEndpoint,ConnectionPolicy connectionPolicy,Nullable`1 desiredConsistencyLevel)
   at Microsoft.Azure.Documents.Client.DocumentClient..ctor(Uri serviceEndpoint,String authKeyOrResourceToken,ConnectionPolicy connectionPolicy,Nullable`1 desiredConsistencyLevel)
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.DocumentDBService..ctor(String connectionString)
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.DefaultDocumentDBServiceFactory.CreateService(String connectionString)
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.DocumentDBConfiguration.<GetService>b__23_0(String c)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key,Func`2 valueFactory)
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.DocumentDBConfiguration.GetService(String connectionString)
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.DocumentDBConfiguration.CreateContext(DocumentDBAttribute attribute)
   at Microsoft.Azure.WebJobs.Extensions.DocumentDB.Bindings.DocumentDBCollectorBuilder`1.Convert(DocumentDBAttribute attribute)
   at Microsoft.Azure.WebJobs.Host.Bindings.PatternMatcher.Invoker`2.<>c__DisplayClass0_0.<Work>b__0(Object input)
   at Microsoft.Azure.WebJobs.Host.Bindings.AsyncCollectorBindingProvider`2.ExactBinding`1.BuildAsync(TAttribute attrResolved,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Bindings.BindingBase`1.BindAsync[TAttribute](??)
   at System.Runtime.ExceptionSe…

**Comment by christopheranderson** [comment]
@guybartal - sorry we missed this issue. Is this still happening?

**Comment by guybartal** [comment]
No, it's okay now. I've recreated the function service. Thanks for replying.
