### ISSUE TITLE
Inconsistent behavior processing HTTP protocol violations between Azure Functions and Function Proxies

### ISSUE THREAD

**Issue by baabel** [Azure/azure-webjobs-sdk-script#2084]
When POSTing an HTTP request to an Azure Function Proxy where the Content-Length header value is set to 0 and there is data in the body, the Proxy forwards the request to the back end service with an empty body and the Proxy ends up throwing and logging a protocol exception and returns 500 to the user agent.

POSTing the same HTTP request directly to an Azure Function does not result in an exception and the Function successfully reads the body despite the content length value specified as 0.

#### Repro steps

1. Create an HTTP Trigger Function
2. Create an Azure Functions Proxy that forwards to #1
3. POST a request with data in the body to the Azure Function with Content-Length set to 0
    The function will successfully read the request body and process the request normally.
4. POST a request to the Azure Function Proxy with data in the body and the Content-Length set to 0.
    The proxy will forward the request to the Azure Function with an empty body
    The proxy will log an exception and return 500 back to the user agent

**Exception thrown by PROXY RUNTIME:**

System.Net.ProtocolViolationException: Bytes to be written to the stream exceed the Content-Length bytes size specified.
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.Azure.AppService.Proxy.Common.Extensions.StreamExtensions.<WriteAndFlushAsync>d__1.MoveNext() in e:\bt\849565\repo\src\microsoft.azure.appservice.proxy.common\Contracts\Extensions\StreamExtensions.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Proxy.Common.Extensions.StreamExtensions.<CopyStreamToStreamAsync>d__0.MoveNext() in e:\bt\849565\repo\src\microsoft.azure.appservice.proxy.common\Contracts\Extensions\StreamExtensions.cs:line 64

#### Expected behavior

Consistent behavior between Azure Functions and Proxies.

#### Actual behavior

Proxies throws an exception and returns 500 to the user agent

Functions successfully processes the request

#### Related information 

* c#
* Links to source
* HTTP

**Comment by safihamid** [comment]
This is working fine for me. what version of functions runtime are you using? Mine is Runtime version: 1.0.11360.0 (~1) hich is the latest version.

**Comment by safihamid** [comment]
This cannot be repro'd from our side. Can you please verify you are running the latest runtime version of Functions, and copy/paste your exact http trace?

**Comment by safihamid** [comment]
Closing this one as the other one #2099 is more relevant.
