### ISSUE TITLE
Getting occasional memory exceptions just doing simple save/run operations

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#211]
I've seen that a few times. I'm just writing a function and hitting run as I make changes. Nothing too intense.

```
2016-04-01T19:52:20  Welcome, you are now connected to log-streaming service.
2016-04-01T19:52:33.146 Function completed (Failure)
2016-04-01T19:52:33.179 Exception while executing function: Functions.GitHubCSharp1. mscorlib: Insufficient memory to continue the execution of the program.
```

Maybe there is some kind of leak? Note that I have the container size set to 256MB, which is twice the default. So that really shouldn't be happening.

**Comment by brettsam** [comment]
I ran into this yesterday as well but didn't have a good repro. I was hoping to catch it today and do more investigation but it hasn't happened. My site app was using default settings.

**Comment by mathewc** [comment]
We had some OOM exceptions before and @fabiocav submitted https://github.com/Azure/azure-webjobs-sdk-script/commit/42e5029f814a74e072f9db770a652ccc7cb35476 in an attempt to fix. Maybe its still not fixed.

**Comment by fabiocav** [comment]
I'll investigate this. I was chatting with @brettsam when he ran into this issue yesterday and I think this is unrelated to what we fixed with 42e5029. Do we don't have the full stack logged anywhere for those exceptions, do we?

**Comment by davidebbo** [comment]
For te specific instance of the issue, there is nothing useful in the host log.

However, I did find a stack for a different time (an hour earlier), but it may be a distinct issue:

```
2016-04-01T18:42:51.084 System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(RuntimeAssembly containingAssembly, Boolean emitSymbolInfo, String name, String filename, StackCrawlMarkHandle stackMark, IntPtr& pInternalSymWriter, ObjectHandleOnStack retModule, Boolean fIsTransient, Int32& tkFile)
   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(RuntimeAssembly containingAssembly, Boolean emitSymbolInfo, String name, String filename, StackCrawlMark& stackMark, IntPtr& pInternalSymWriter, Boolean fIsTransient, Int32& tkFile)
   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModuleInternalNoLock(String name, String fileName, Boolean emitSymbolInfo, StackCrawlMark& stackMark)
   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModuleInternal(String name, String fileName, Boolean emitSymbolInfo, StackCrawlMark& stackMark)
   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(String name, String fileName)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Generate(String functionAssemblyName, String typeName, Collection`1 functions)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize()
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(ScriptHostConfiguration scriptConfig)
   at Microsoft.Azure.WebJobs.Script.ScriptHostFactory.Create(ScriptHostConfiguration config)
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken)
```

**Comment by fabiocav** [comment]
Yeah. Looks like a different issue than what we were dealing with. This actually ran out of memory while trying to create the "proxy" Functions type (which is the step all functions go through, regardless of language), probably as a result of a host reload. I'll look at this, but based on the flow you described above, I have a pretty good idea of what is going on.

**Comment by mathewc** [comment]
I'm also seeing these OOM again when debugging locally. Just now for example:

System.OutOfMemoryException was unhandled by user code
  HResult=-2147024882
  Message=Insufficient memory to continue the execution of the program.
  Source=mscorlib
  StackTrace:
       at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
       at System.Runtime.InteropServices.Marshal.AllocHGlobal(Int32 cb)
       at System.Reflection.Internal.NativeHeapMemoryBlock..ctor(Int32 size)
       at System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(Stream stream, Boolean isFileStream, Int64 start, Int32 size)
       at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options, Nullable`1 sizeOpt)
       at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options)
       at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)
       at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
       at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver.<>c.<.ctor>b__8_0(String path, MetadataReferenceProperties properties)
       at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties)
       at Microsoft.CodeAnalysis.Scripting.ScriptMetadataResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties)
       at Microsoft.Azure.WebJobs.Script.Description.FunctionMetadataResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties) in C:\code\Git\Azure\azure-webjobs-sdk-script\src\WebJobs.Script\Description\CSharp\FunctionMetadataResolver.cs:line 130
       at Microsoft.CodeAnalysis.Scripting.Script.GetReferencesForCompilation(CommonMessageProvider messageProvider, DiagnosticBag diagnostics, MetadataReference languageRuntimeReferenceOpt)
       at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScriptCompiler.CreateSubmission(Script script)
       at Microsoft.CodeAnalysis.Scripting.Script.GetCompilation()
       at Microsoft.Azure.WebJobs.Script.Description.CSharpFunctionInvoker.GetScriptCompilation(Script`1 script, Boolean debug) in C:\code\Git\Azure\azure-webjobs-sdk-script\src\WebJobs.Script\Description\CSharp\CSharpFunctionInvoker.cs:line 389
       at Microsoft.Azure.WebJobs.Script.Description.CSharpFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) in C:\code\Git\Azure\azure-webjobs-sdk-script\src\WebJobs.Script\Description\CSharp\CSharpFunctionInvoker.cs:line 297
       at Microsoft.Azure.WebJobs.Script.Description.FunctionValueLoader.<>c__DisplayClass2_0.<.ctor>b__1() in C:\code\Git\Azure\azure-webjobs-sdk-script\src\WebJobs.Script\Description\CSharp\FunctionValueLoader.cs:line 23
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException:

**Comment by fabiocav** [comment]
Yeah, looks like that issue is still lurking. I'll investigate.

**Comment by fabiocav** [comment]
@mathewc, @davidebbo I have not spent much time on this issue, but was looking at it and wanted to check if this is something you're still seeing. I haven't experienced this in recent builds but wanted to check if this is something you're still running into.

**Comment by davidebbo** [comment]
I haven't had that much time to play with functions in past week or two, so I don't really have a recent data point. I'll look out for it.

**Comment by mathewc** [comment]
I can't remember seeing it in a while either. Feel free to close this if you'd like and we can reopen if we or customers see this.

**Comment by fabiocav** [comment]
Closing this for now. Will reopen if required.

**Comment by Kanika23m** [comment]
I am getting the similar issue "{"Insufficient memory to continue the execution of the program."}"  at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb).

Code Snippet : 
 public IntPtr funcaddrMngEPTR_EngineCycleTemp;
 public IntPtr dllHandle;
//Load
                this.dllHandle = UnsafeMethods.LoadLibraryA(this.model.OutputDLLPath);
                if (dllHandle == IntPtr.Zero)
                {
                    int errorCode = Marshal.GetLastWin32Error();
                    throw new Exception(string.Format("Failed to load library (ErrorCode: {0})", errorCode));
                };

funcaddrMngEPTR_EngineCycleTemp = Marshal.AllocHGlobal(UnsafeMethods.GetProcAddress(dllHandle, "_EngineCycle_Sim"));
