### ISSUE TITLE
Node runtime version is inconsistent with console version

### ISSUE THREAD

**Issue by bondz** [Azure/azure-webjobs-sdk-script#2160]
When using Node 8.9.0 with native support for async await, async function entry points do not work as function invocation.

Testing using the console works.

#### Investigative information

- Timestamp: `2017-11-27T18:29:48.290`
- Function App version (1.0 or 2.0-beta): `~1.0` `1.0.11388.0`
- Invocation ID: `7e94b5c4-b789-4cee-9b4b-f87ee87963fc`
- Region: `West-Europe`

#### Repro steps
```js
async function reproFunction(context, myTimer) {
   return Promise.resolve('done');
}

module.exports = reproFunction;
```

#### Expected behavior

Should succeed with Node 8

#### Actual behavior

```text
2017-11-27T18:33:47.266 Exception while executing function: Functions.xxx. mscorlib: One or more errors occurred. D:\home\site\wwwroot\xxx\build\index.js:7
async function reproFunction(context, myTimer) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at eval (eval at compileFunc (D:\Program Files (x86)\SiteExtensions\Functions\1.0.11388\bin\edge\double_edge.js:34:28), <anonymous>:1:80).
2017-11-27T18:33:47.344 Function completed (Failure, Id=d3aac6fc-8395-428a-930e-93e232800e54, Duration=239ms)
```

#### Related information 

Provide any related information 

* Programming language used: Typescript -> JS

**Comment by bondz** [comment]
I have the environment variable `WEBSITE_NODE_DEFAULT_VERSION` set to `8.9.0`
running `node --version` in any console logs `8.9.0`

But I just tried, 

```js
function reproFunction(context, timer) {
context.log(process.version)
}
``` 

and I get `v6.11.2`

That's the source of the problem. Is there a way to change the runtime version of nodejs to match the one used in the console?

**Comment by fabiocav** [comment]
Are you running V1 or V2 (beta) when on Azure?

**Comment by bondz** [comment]
@fabiocav I'm running v1

**Comment by bondz** [comment]
@fabiocav I'm running v1

**Comment by fabiocav** [comment]
Unfortunately, in V1, you cannot change the Node version used by Azure Functions, as we're locked to what we build against. This is one of the benefits of the new V2 model.
