### ISSUE TITLE
Azure Functions Node.Js app fails when using web3.js to make a connection to an Ethereum Server

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-webjobs-sdk-script#2166]
#### Investigative information

Please provide the following:

- Timestamp:11-05-2017 
- Function App version (1.0 or 2.0-beta):1.0
- Function App name: (Not Shared)
- Function name(s) (as appropriate): Function.EnvironmentAlert
- Invocation ID: 677660dd-b785-44a9-b5ce-7a50b8c4ff8c
- Region: Hong Kong

#### Repro steps

Provide the steps required to reproduce the problem:

Step A 
1) Configure an Ethereum Server in Azure using the MarketPlace template.
2) Configure an Azure Function to connect to the above instance using the code below. 

#### Expected behavior

Provide a description of the expected behavior.
1) The connection to the Ethereum will succeed.

#### Actual behavior

Provide a description of the actual behavior observed.

The following error is logged.

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.EnvironmentAlert ---> System.Exception : Error: CONNECTION ERROR: Couldn't connect to node http://13.68.218.47:8545.
    at Object.InvalidConnection (D:\home\site\wwwroot\EnvironmentAlert\node_modules\web3\lib\web3\errors.js:31:16)
    at HttpProvider.send (D:\home\site\wwwroot\EnvironmentAlert\node_modules\web3\lib\web3\httpprovider.js:83:22)
    at RequestManager.send (D:\home\site\wwwroot\EnvironmentAlert\node_modules\web3\lib\web3\requestmanager.js:58:32)
    at Eth.get [as accounts] (D:\home\site\wwwroot\EnvironmentAlert\node_modules\web3\lib\web3\property.js:107:62)
    at module.exports (D:\home\site\wwwroot\EnvironmentAlert\index.js:17:41)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.11360\bin\azurefunctions\functions.js:99:24
   at async Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Description\Node\NodeFunctionInvoker.cs : 194
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 90
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)

#### Known workarounds

Provide a description of any known workarounds.

It will work if you do these three things.

1) Run under Functions 2.0 beta runtime 
2) Run as an App Service Plan.
3) Enable WebSockets.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

https://stackoverflow.com/questions/47054564/call-ethereum-using-web3-js-on-azure-function

<details>
<summary>Source</summary>

```Node.Js

'use strict';

module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function for BlockChain processed a request.');

    var tx = process.env.TX_NODE_URL;
    var passpharse = process.env.PRODUCER_PASSPHRASE;
    var fs = require('fs');
    var Web3 = require('web3');
    var web3 = new Web3();
    var text = fs.readFileSync('./HttpTriggerJS/contracts/IoTEnvironmentSummary.json', 'utf8');//truffle compile result
    web3.setProvider(new web3.providers.HttpProvider("http://52.170.114.107:8545"));
    web3.personal.unlockAccount(web3.eth.accounts[0], passpharse);
    var contractInterface = JSON.parse(text);
    var alertContract = web3.eth.contract(contractInterface.abi).new({ from: web3.eth.accounts[0], data: contractInterface.unlinked_binary, gas: 3000000 });
    context.log('After the Web 3 commands');
    context.res = {
        body: "Hello World"
    };
    context.done();
};


```
</details>

**Comment by FinVamp1** [comment]
The customer confirmed that the WebSocket setting wasn’t needed just the Beta runtime change and this applies to both Consumption and ASP.

**Comment by christopheranderson** [comment]
This is likely due to a native module issue which we can't fix for v1 due to our reliance on edge.js.

Closing won't fix. This should work in v2 just fine (as indicated in the workarounds)
