### ISSUE TITLE
App insight causing script host initialization failure. Causes admin api to fetch master key fail

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#2173]
I see several customer getting this error. If the customer ends up opening the portal at the time. He would be getting the red balloon pop-up and would not be able to manage the site. The strange thing is we don't see logs regarding admin api failures anywhere because of this.

```
System.Security.Principal.IdentityNotMappedException : Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts,Type targetType,Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification,AccessRule rule,Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.ApplicationFolderProvider.CreateTelemetrySubdirectory(DirectoryInfo root)
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.ApplicationFolderProvider.CreateAndValidateApplicationFolder(String rootPath,Boolean createSubFolder,IList`1 errors)
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.ApplicationFolderProvider.GetApplicationFolder()
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.TransmissionStorage.Initialize(IApplicationFolderProvider applicationFolderProvider)
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.Transmitter.Initialize()
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel.Initialize(TelemetryConfiguration configuration)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.DefaultTelemetryClientFactory.InitializeConfiguration()
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.DefaultTelemetryClientFactory.Create()
   at Microsoft.Azure.WebJobs.Script.ScriptTelemetryClientFactory.Create() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptTelemetryClientFactory.cs : 25
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider..ctor(ITelemetryClientFactory clientFactory)
   at Microsoft.Extensions.Logging.ApplicationInsightsLoggerExtensions.AddApplicationInsights(ILoggerFactory loggerFactory,ITelemetryClientFactory telemetryClientFactory)
   at Microsoft.Azure.WebJobs.Script.DefaultLoggerFactoryBuilder.AddLoggerProviders(ILoggerFactory factory,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Diagnostics\DefaultLoggerFactoryBuilder.cs : 30
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ConfigureLoggerFactory(ScriptHostConfiguration scriptConfig,IFunctionTraceWriterFactory traceWriteFactory,ScriptSettingsManager settingsManager,Func`1 isFileLoggingEnabled) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 654
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ConfigureDefaultLoggerFactory() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 646
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 388
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment,IScriptEventManager eventManager,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager,ProxyClientExecutor proxyClient) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 806
```

**Comment by brettsam** [comment]
This technically isn't related to App Insights. There are other issues with this specific customer and this error no longer repros.
