### ISSUE TITLE
Logfile contention caused Job host to fail in multiple instance scenario

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-webjobs-sdk-script#31]
This [line](https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script/FileTraceWriter.cs#L31) cause multiple instances to use the same log file and failed in multiple instances.   Suggestion would be to (similar to Kudu) add machine name in file name and time stamp to help with gc old log files.

```c#
2016-02-25T01:49:42 System.IO.IOException: The process cannot access the file 'D:\home\LogFiles\Application\Functions\Host\561a87bf-dc59-49d7-a7d4-7c3fc023fe19.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   at System.IO.File.AppendAllText(String path, String contents)
   at Microsoft.Azure.WebJobs.Script.FileTraceWriter.AppendLine(String line)
   at Microsoft.Azure.WebJobs.Script.FileTraceWriter.Trace(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.InvokeTraceWriters(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.Trace(TraceEvent traceEvent)
   at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.LogFunctionStartedAsync(FunctionStartedMessage message, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Host.Loggers.CompositeFunctionInstanceLogger.<LogFunctionStartedAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__1.MoveNext()

```

**Comment by davidebbo** [comment]
Good catch. Also, it's have the name start with a sortable date so they show in proper order when doing a dir.

**Comment by davidebbo** [comment]
Yes, I just ran into this as well.

**Comment by mathewc** [comment]
Ok, the logging issue is a bigger blocker than I thought. I put something tactical in place with TODOs on making it more robust. I'll get to this soon.

**Comment by mathewc** [comment]
Resolved by https://github.com/Azure/azure-webjobs-sdk-script/commit/77fd867f6c23a336745e1220bb984b2b2ff76aba. We now include machine instance ID (or machine name) in all log file names.
