### ISSUE TITLE
Simple queue trigger and blob output function app is fail occasionally.

### ISSUE THREAD

**Issue by buchizo** [Azure/azure-webjobs-sdk-script#411]
In the case of Function App to output the contents of the queue to the Blob, an error may occur when the queue has been a large amount registered.

Sample source: https://gist.github.com/buchizo/71d6f16cb623ee764186985d1881b1b9

Error information: Failure: Error while handling parameter outputBlob after function returned: 400 Bad request.
Exception details:

`...at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Blobs.Bindings.WatchableCloudBlobStream.<CommitAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Blobs.Bindings.OutStringArgumentBindingProvider.StringArgumentBinding.StringValueBinder.<SetValueAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__33.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__15.MoveNext()
   --- End of inner exception stack trace ---`

If an error occurs, the queue is removed, And blob is not output. That will not be retried.

**Comment by christopheranderson** [comment]
We need to improve our error handling to so we can see what's going wrong here.

**Comment by mathewc** [comment]
Thanks for providing the detailed repro code. We'll try to repro/fix this as soon as we can.

**Comment by brettsam** [comment]
@pragnagopa -- can you try to repro this and see what the issue is?

**Comment by pragnagopa** [comment]
I cannot repro this error. @buchizo let us know if you still see the issue with latest runtime
