### ISSUE TITLE
AccessViolations logged to EventLog.xml

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#425]
From time to time I'm seeing Access Violations logged to the site **eventlog.xml** file. The one below is coming from the core WebJobs SDK template binding code. Need to get a repro and fix.

<Events>
    <Event>
        <System>
            <Provider Name=".NET Runtime"/>
            <EventID>1026</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2016-05-26T19:52:23Z"/>
            <EventRecordID>737302703</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FFB368F9</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at DynamicClass.Go20(System.Text.RegularExpressions.RegexRunner)
   at System.Text.RegularExpressions.CompiledRegexRunner.Go()
   at System.Text.RegularExpressions.RegexRunner.Scan(System.Text.RegularExpressions.Regex, System.String, Int32, Int32, Int32, Int32, Boolean, System.TimeSpan)
   at System.Text.RegularExpressions.Regex.Run(Boolean, Int32, System.String, Int32, Int32, Int32)
   at System.Text.RegularExpressions.Regex.Match(System.String, Int32)
   at System.Text.RegularExpressions.Regex.Match(System.String)
   at Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplateSource.CreateBindingData(System.String)
   at Microsoft.Azure.WebJobs.Host.Blobs.ParameterizedBlobPathSource.CreateBindingData(Microsoft.Azure.WebJobs.Host.Blobs.BlobPath)
   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobTriggerExecutor+&lt;ExecuteAsync&gt;d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobTriggerExecutor+&lt;ExecuteAsync&gt;d__1, Microsoft.Azure.WebJobs.Host, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](&lt;ExecuteAsync&gt;d__1 ByRef)
   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobTriggerExecutor.ExecuteAsync(Microsoft.Azure.WebJobs.Host.Storage.Blob.IStorageBlob, System.Threading.CancellationToken)
   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy+&lt;NotifyRegistrationsAsync&gt;d__1b.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Azure.WebJobs.Host.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy+&lt;NotifyRegistrationsAsync&gt;d__1b, Microsoft.Azure.WebJobs.Host, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](&lt;NotifyRegistrationsAsync&gt;d__1b ByRef)
   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.NotifyRegistrationsAsync(Microsoft.Azure.WebJobs.Host.Storage.Blob.IStorageBlob, System.Collections.Generic.ICollection`1&lt;Microsoft.Azure.WebJobs.Host.Storage.Blob.IStorageBlob&gt;, System.Threading.CancellationToken)
   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy+&lt;PollAndNotify&gt;d__c.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()

**Comment by mathewc** [comment]
We need to see if this is still happening, and if some make the requisite core SDK fixes.
