### ISSUE TITLE
Error executing Sample QueueTrigger-Python

### ISSUE THREAD

**Issue by dev-ankit** [Azure/azure-webjobs-sdk-script#476]
HI I'm trying to run the python script given in the samples folder but I get the following error when it is triggered.

> Found the following functions:
Host.Functions.QueueTrigger-Python
Job host started
Executing: 'Functions.QueueTrigger-Python' - Reason: 'New queue message detected on 'myqueue'.'
  Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is 'a641ef11-c098-41e9-9815-d800de75728e'
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.QueueTrigger-Python ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Azure.WebJobs.Script.Description.ScriptFunctionInvoker.InitializeEnvironmentVariables(Dictionary`2 environmentVariables, String functionInstanceOutputPath, Object input, Collection`1 outputBindings, ExecutionContext context)
   at Microsoft.Azure.WebJobs.Script.Description.ScriptFunctionInvoker.<ExecuteScriptAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Script.Description.ScriptFunctionInvoker.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__2e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__2.MoveNext()

 The sample runs fine if I replace the python file with a Node.js file. I have installed python 3.5 (64bit) on my machine and have added it to the PATH
**EDIT**
Figured out the solution. Needed to add Microsoft.AspNet.WebApi.Core NuGet package. Shouldn't it be added as a dependency?

**Comment by mathewc** [comment]
I had just tried to repro from our WebJobs.Script.sln but couldn't. Can you please provide the exact setup steps you used to hit this error? You may be right that we are missing a package dependency.

**Comment by dev-ankit** [comment]
1. I added a new console application from VS2015 enterprise.
2. added the Microsoft.Azure.WebJobs.Script from nuget 
3. used the sample code for Program.cs (as mentioned in project wiki), host.json, function.json and queueTrigger.py
it gave me the error that I've mentioned above. But, after I installed Microsoft.AspNet.WebApi.Core package to the project, it worked fine

**Comment by mathewc** [comment]
Thanks. I'll repro myself, and we'll get our package dependencies fixed, thanks.

**Comment by mathewc** [comment]
Package has now been fixed, thanks for reporting. Version 1.0.0-alpha1-10286 has the updated nuget dependency.
