### ISSUE TITLE
format exception causing scripthost to continually restart

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#483]
Hi,

A bunch of my jobs are causing the following error to occur, which is sending the scripthost into a cycle of constantly restarting:

```
[07/08/2016 19:26:28 > cfb1f8: ERR ] Unhandled Exception: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Convert.FromBase64String(String s)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage.get_AsString()
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at Microsoft.Azure.WebJobs.Host.Queues.StorageQueueMessageExtensions.TryGetAsString(IStorageQueueMessage message)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at Microsoft.Azure.WebJobs.Host.Queues.QueueCausalityManager.GetOwner(IStorageQueueMessage msg)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueTriggerExecutor.<ExecuteAsync>d__1.MoveNext()
[07/08/2016 19:26:28 > cfb1f8: ERR ] --- End of stack trace from previous location where exception was thrown ---
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.<ProcessMessageAsync>d__11.MoveNext()
[07/08/2016 19:26:28 > cfb1f8: ERR ] --- End of stack trace from previous location where exception was thrown ---
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[07/08/2016 19:26:28 > cfb1f8: ERR ]    at System.Threading.ThreadHelper.ThreadStart()
[07/08/2016 19:26:28 > cfb1f8: SYS ERR ] Job failed due to exit code -532462766
```

Unfortunately, I haven't been able to narrow it down to a specific job and the error isn't super helpful. Any idea what might be triggering this?

Thanks,
James

**Comment by jamesdixon** [comment]
I tracked the issue down to the queue message I've been inserting not being encoded as base64. This appears to be a change in the way things previously worked as I've never had a problem until now. 

Is this something that you're aware of?

**Comment by jamesdixon** [comment]
Note that the message I'm inserting is JSON, which no longer throws the above error, but it appears that the message is no longer parsed into an object.

**Comment by mathewc** [comment]
Hmmm, no I'm not aware of any issues. Note that we have lots of tests that are enqueueing json strings w/o encoding them in any special way, e.g. https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/test/WebJobs.Script.Tests/SamplesEndToEndTests.cs#L270.

Can you provide complete repro code, showing how you're adding the message?

**Comment by jamesdixon** [comment]
I did see the tests, which is why I'm extra confused 😄 

In terms of adding the message, I'm not doing anything special:

```js
const queueService = Azure.createQueueService();
const message = {
    type: 'forgotPassword',
    email: 'jim.w.dixon@gmail.com',
    firstName: 'James',
    userId: 1
};

queueService.createMessage('email-notifications', JSON.stringify(message), (err, response) => {

                if (err) {
                    throw err;
                }

               return response;
            });
```

I just did some testing and it appears to be a change in the Azure Storage SDK for Node. Running the latest-pre 1.0 version (0.10.0), it looks like the queue message is automatically converted to base64 without any intervention:

![image](https://cloud.githubusercontent.com/assets/110114/16706137/aca24a5e-455d-11e6-8ff1-2865e8727fd0.png)

However, upgrading to 1.x, the message is no longer automatically encoded to base64 and throws the aforementioned error:

![image](https://cloud.githubusercontent.com/assets/110114/16706143/059ec754-455e-11e6-8795-3b243f7896ae.png)

I opened [an issue](https://github.com/Azure/azure-storage-node/issues/165) as it seems like a strange change in behavior.

**Comment by jamesdixon** [comment]
Closing since this appears to be a Azure Node SDK issue

**Comment by jamesdixon** [comment]
@mathewc in case you're interested, here was the response to the issue I posted:

> @jamesdixon , refer to the breaking change log, originally the SDK only support a flag which indicates if the queue message should be encoded/decoded (base64 encoding). But we found that's not enough and not extensible. So we decided to introduce the encoding/decoding interface and provided some built-in encoders. For why we change the default encoding behavior from base64 encoding to XML encoding, it's because XML encoding will have smaller payload size for most scenarios. Please let me know if this makes sense.
