### ISSUE TITLE
CLI: func run failed with 'Append access can be requested only in write-only mode.'

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-webjobs-sdk-script#512]
Ran into below when trying to `func run <funcname>`.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. 
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> System.ArgumentException: Append access can be requested only in write-only mode.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Abstractions.FileWrapper.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at WebJobs.Script.Cli.Common.FileTracer..ctor(TraceLevel level, String filePath)
   at WebJobs.Script.Cli.DependencyResolver.ResolveTraceWriter(TraceLevel info, String logFile)
   at WebJobs.Script.Cli.Verbs.BaseVerb.EnsureTracer()
   at WebJobs.Script.Cli.Verbs.BaseVerb.set_LogFile(String value)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at NCli.ConsoleApp.Parse()
   at NCli.ConsoleApp.RunAsync[T](String[] args, IDependencyResolver dependencyResolver)
   at NCli.ConsoleApp.<>c__DisplayClass1_0`1.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NCli.ConsoleApp.Run[T](String[] args, IDependencyResolver dependencyResolver)
   at WebJobs.Script.Cli.Program.Main(String[] args)
```

**Comment by fabiocav** [comment]
Experiencing the same thing.

**Comment by christopheranderson** [comment]
@ahmelsayed - can you please look at this and see if it's still relevant

**Comment by ahmelsayed** [comment]
Fixed? Maybe, probably. I don't think it's still relevant
