### ISSUE TITLE
Bad error message when using invalid parameters in binding 

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#53]
I used an invalid parameter in my C# queue binding and got an NPE in the script host. There should be a separate step of metadata validation that provides a nicer error message.

I used **path** instead of **queueName**, so I expected an error in the script output window.

In Function.json:
```
{
    "bindings": [
        {
            "type": "queueTrigger",
            "direction": "in",
            "path": "resizerequest" 
        }
}

```
Log output:
```
2016-03-04T02:09:51 System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplateParser.ParseTemplate(String input)
   at Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.GetBindings(ScriptHostConfiguration config, IEnumerable`1 bindingMetadatas, FileAccess fileAccess)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionDescriptorProvider.TryCreate(FunctionMetadata functionMetadata, FunctionDescriptor& functionDescriptor)
   at Microsoft.Azure.WebJobs.Script.Description.CSharpFunctionDescriptionProvider.TryCreate(FunctionMetadata functionMetadata, FunctionDescriptor& functionDescriptor)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ReadFunctions(List`1 metadatas, IEnumerable`1 descriptorProviders)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ReadFunctions(ScriptHostConfiguration config, IEnumerable`1 descriptionProviders)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize()
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(ScriptHostConfiguration scriptConfig)
   at Microsoft.Azure.WebJobs.Script.ScriptHost

```

**Comment by davidebbo** [comment]
This is a case of error handling that we should improve.

**Comment by mathewc** [comment]
Yeah, this is has been something I've been meaning to get to. Assigning to me since it needs to be handled across the board.
