### ISSUE TITLE
w3wp terminated due to unhandled exception

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#555]
I saw w3wp crashing with the exception below logged in eventlog.xml

I think it happens when I touch host.json while a bunch of queue functions are running.

``` csharp
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(System.Action`1&lt;System.Object&gt;, System.Object, System.Threading.SynchronizationContext, System.Threading.ExecutionContext)
   at System.Threading.CancellationToken.Register(System.Action`1&lt;System.Object&gt;, System.Object, Boolean, Boolean)
   at System.Threading.CancellationToken.Register(System.Action)
   at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer+&lt;StopAsyncCore&gt;d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener+&lt;ProcessMessageAsync&gt;d__11.MoveNext()
   at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher+&lt;&gt;c__DisplayClass1.&lt;Throw&gt;b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by ahmelsayed** [comment]
Actually now it seems to be happening without touching host.json

**Comment by mathewc** [comment]
This might be tough since there is no clear repro. We might have some issues on our dispose paths.

**Comment by ahmelsayed** [comment]
This was also a long time ago, if the info in the stack at the top are not meaningful, I'd just close this bug

**Comment by mathewc** [comment]
Agreed. Closing.
