### ISSUE TITLE
EventHub Message Duplication

### ISSUE THREAD

**Issue by jcawth** [Azure/azure-webjobs-sdk-script#599]
I am using a function that Chris And. sent me to generate exponential load up to a certain generation n (2^n). In total this generates 2^(n+1) - 1 messages. Each message taken from the event hub #1 sends 2 new messages each with a unique Guid to event hub #1, and then sends itself to eventhub #2 for logging. A second function simply logs all the messages from event hub #2. I used a short python script to parse for the number of distinct Guids from the second function's logs, and the number of total Guids and save the duplicates so i could find them in the logs. I ran a test with a generation size of 16, and found 131070 distinct Guids (the expected number) but 3028 additional duplicates.  A couple things about this are strange. The duplicates that i saw (there were thousands so i didnt look at them all) were each processed on the same machines, but were not duplicate log entries because the function id was different. I also noticed that some of the duplicates occurred as the last 155 entries of one of the logs and the first 155 entries of another one of the logs. Attached is the code for the two functions, the telem function logs, and the output of the python script.

[pythonOut.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431243/pythonOut.txt)

[funcCode_wwwroot.zip](https://github.com/Azure/azure-webjobs-sdk-script/files/431222/funcCode_wwwroot.zip)

[2016-08-19T21-02-32Z-3db63119cf.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431250/2016-08-19T21-02-32Z-3db63119cf.log.txt)

[2016-08-19T21-02-33Z-7b8ae827ba.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431253/2016-08-19T21-02-33Z-7b8ae827ba.log.txt)
[2016-08-19T21-02-33Z-d059c3b193.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431251/2016-08-19T21-02-33Z-d059c3b193.log.txt)
[2016-08-19T21-02-56Z-aeda3353d0.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431255/2016-08-19T21-02-56Z-aeda3353d0.log.txt)
[2016-08-19T21-04-07Z-188e2568d4.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431252/2016-08-19T21-04-07Z-188e2568d4.log.txt)
[2016-08-19T21-04-13Z-3ad9588627.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431256/2016-08-19T21-04-13Z-3ad9588627.log.txt)
[2016-08-19T21-15-26Z-afdeb2eba0.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431254/2016-08-19T21-15-26Z-afdeb2eba0.log.txt)
[2016-08-19T21-22-46Z-032af8bf3a.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431258/2016-08-19T21-22-46Z-032af8bf3a.log.txt)
[2016-08-19T21-23-49Z-cc28ac7ae8.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431259/2016-08-19T21-23-49Z-cc28ac7ae8.log.txt)
[2016-08-19T21-25-12Z-e97899ef81.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431257/2016-08-19T21-25-12Z-e97899ef81.log.txt)
[2016-08-19T21-27-57Z-24141a2f24.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431260/2016-08-19T21-27-57Z-24141a2f24.log.txt)
[2016-08-19T21-29-29Z-d059c3b193.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431262/2016-08-19T21-29-29Z-d059c3b193.log.txt)
[2016-08-19T21-30-00Z-61d0ba363b.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431261/2016-08-19T21-30-00Z-61d0ba363b.log.txt)
[2016-08-19T21-32-03Z-bbb85071ab.log.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/431263/2016-08-19T21-32-03Z-bbb85071ab.log.txt)

**Comment by MikeStall** [comment]
PartitionContext.CheckpointAsync() is failing. So the event batch gets retried. 

Microsoft.ServiceBus.Messaging.LeaseLostException occurred
  HResult=-2146233088
  Message=Exception of type 'Microsoft.ServiceBus.Messaging.LeaseLostException' was thrown.
  Source=Microsoft.ServiceBus.Messaging.EventProcessorHost
  StackTrace:
       at Microsoft.ServiceBus.Messaging.BlobLeaseManager.<UpdateAsync>d__23.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.ServiceBus.Messaging.BlobLeaseManager.<CheckpointAsync>d__24.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.Azure.WebJobs.ServiceBus.EventHubListener.<Microsoft-ServiceBus-Messaging-IEventProcessor-ProcessEventsAsync>d__10.MoveNext() in C:\dev\AFunc\azure-webjobs-sdk\src\Microsoft.Azure.WebJobs.ServiceBus\EventHubs\EventHubListener.cs:line 97
  InnerException: 
       HResult=-2146233088
       Message=The remote server returned an error: (409) Conflict.
       Source=Microsoft.WindowsAzure.Storage
       StackTrace:
            at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
            at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndRenewLease(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 1979
            at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 114
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Microsoft.ServiceBus.Messaging.BlobLeaseManager.<UpdateAsync>d__23.MoveNext()
       InnerException: 
            HResult=-2146233079
            Message=The remote server returned an error: (409) Conflict.
            Source=Microsoft.WindowsAzure.Storage
            StackTrace:
                 at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50
                 at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.<>c__DisplayClass33.<RenewLeaseImpl>b__32(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 3183
                 at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299
            InnerException:

**Comment by MikeStall** [comment]
It's receiving events 1 at  time. Use the array binding syntax to receive in batch - that will be much faster and help 

Technically, EH events can be duplicated (similar to Azure queue messages). But it should be a low rate. For example, if the machine crashes after processing the event but before calling PartitionContext.CheckpointAsync(), then events would get processed again. 
PartitionContext is failing because it's not keeping up with the high throughput.  This could be because of failing to renew the lease (Outbound network gets starved and can't make the renewal call, CPU gets too starved, etc)

**Comment by MikeStall** [comment]
This is technically "by design" (events can be duplicated). User should switch to receiving as an array rather than a single item. 
I'll investigate better throughput to minimize the duplication.

**Comment by MikeStall** [comment]
The recommend fix here is to switch to receive as an array. We ran perf benchmarks on that and found throughput competitive to using EventHostProcessor directly.
