### ISSUE TITLE
Improve NodeFunctionInvoker error handling

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#77]
GitHub WebHook always returns returns the following error when invoked via the "Run Now" endpoint:

```
{
   "_body":"{\"Message\":\"An error has occurred.\"}",
   "status":500,
   "statusText":"Ok",
   "headers":{
     "Pragma":["no-cache"],
     "Date":["Thu"," 10 Mar 2016 05:16:34 GMT"],
     "Server":["Microsoft-IIS/8.0"],
     "X-AspNet-Version":["4.0.30319"],
     "instance-name":["functions-bay"],
     "X-Powered-By":["ASP.NET"],
     "Content-Type":["application/json; charset=utf-8"],
     "Cache-Control":["no-cache"],
     "Content-Length":["36"],
     "Expires":["-1"]
  },
  "type":2,
  "url":"**URL HERE**"
}
```

Ideally this would work like the Generic WebHook where it will pass the content through as JSON.

**Comment by mathewc** [comment]
What does you function script look like? Are you expecting that the input body is JSON or an object?

**Comment by davidebbo** [comment]
Actually, generic webhook is broken the same way.and repros with a trivia function:

```
module.exports = function (context, data) {
    context.done();
}
```

The error in the trace is:

```
2016-03-10T20:23:42 The given key was not present in the dictionary.
2016-03-10T20:23:42 System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.CreateScriptExecutionContext(Object input, TraceWriter traceWriter, TraceWriter fileTraceWriter, IBinder binder, ExecutionContext functionExecutionContext)
   at Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.<Invoke>d__15.MoveNext()
```

**Comment by christopheranderson** [comment]
Code:

```
module.exports = function (context, data) {
    context.log('GitHub WebHook triggered! ' + data.comment.body);
    context.res = {body: 'New GitHub comment: ' + JSON.stringify(data.comment.body, null, " ") };
    context.done();
}
```

Data:

```
{
    "comment": {
        "body": "Hello world"
    }
}
```

function.json
```
{
  "disabled": false,
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "webHookType": "github"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

**Comment by mathewc** [comment]
I looked into this - this is happening because the portal isn't sending a application/json Content-Type. See https://github.com/projectkudu/WebJobsPortal/issues/48

**Comment by davidebbo** [comment]
Keeping open to track improving error handling, since the `KeyNotFoundException` is not ideal. But lower pri.

**Comment by mathewc** [comment]
Retitling

**Comment by mathewc** [comment]
Unable to repro the KeyNotFound anymore. When the content-type is not sent, the request is rejected early now.
