### ISSUE TITLE
Yeoman doesn't get installed with azurefunctions with npm 3+, breaks func new

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#790]
## Error:

func new breaks on new installs with npm 3+

```
E:\workspace> nvm use 6.6.0 32
Now using node v6.6.0 (32-bit)
E:\workspace> npm i -g azurefunctions@latest
C:\Program Files\nodejs\func -> C:\Program Files\nodejs\node_modules\azurefunctions\lib\main.js
C:\Program Files\nodejs\azurefunctions -> C:\Program Files\nodejs\node_modules\azurefunctions\lib\main.js
C:\Program Files\nodejs
+-- azurefunctions@0.2.5
| `-- chalk@1.1.3
|   +-- ansi-styles@2.2.1
|   +-- escape-string-regexp@1.0.5
|   +-- has-ansi@2.0.0
|   | `-- ansi-regex@2.0.0
|   +-- strip-ansi@3.0.1
|   `-- supports-color@2.0.0
+-- UNMET PEER DEPENDENCY generator-azurefunctions@^0.1.6
`-- UNMET PEER DEPENDENCY yo@^1.8.4

npm WARN azurefunctions@0.2.5 requires a peer of generator-azurefunctions@^0.1.6 but none was installed.
npm WARN azurefunctions@0.2.5 requires a peer of yo@^1.8.4 but none was installed.
E:\workspace> func new
module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Users\foobar\AppData\Roaming\nvm\v6.6.0\node_modules\yo\lib\cli.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3


Tip: run `func run <functionName>` to run the function.
```
## Repro:
1. Clear any existing azurefunctions installation
2. Use npm 3+
3. npm i -g azurefunctions@latest
4. func new
## Details:

This is due to the fact that npm 3+ no longer supports grabbing peer dependencies:

Message when installing with npm 2.x (but works fine for install):

```
npm WARN peerDependencies The peer dependency generator-azurefunctions@^0.1.6 included from azurefunctions will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency yo@^1.8.4 included from azurefunctions will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
## Mitigation

You can install them yourself:

```
npm install -g yo generator-azurefunctions
```
## Suggestion
1. Make yo and generator-azurefunctions a dependency
2. (alternative) handle them not existing gracefully, and tell folks to install them themselves

**Comment by lindydonna** [comment]
We'll revisit yeoman installation post-RC

**Comment by lindydonna** [comment]
Closing this as we're already revisiting the entire yeoman dependency.
