### ISSUE TITLE
Nuget restore fails locally using the CLI

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#799]
Package Restore takes a dependency on kudu existing

You get a host error on attempting and failing:

```
2016-10-23T03:46:57.387 Executed: 'Functions.cs-http' (Succeeded)
2016-10-23T03:47:11.685 Restoring packages.
2016-10-23T03:47:11.685 Package restore failed:
2016-10-23T03:47:11.685 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\siteextensions\kudu'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
```

Additionally, finding this error is hard since it is in the host logs. It might be good to surface host and function logs in the cli console window.

**Comment by christopheranderson** [comment]
I was able to partially mitigate this by:

1. Setting my Nuget path here: `$env:AzureWebJobs_NuGetPath`
2. Running `nuget.exe restore` manually

I get this error when modifying the project.json, thus requiring manual restore:

```
2016-10-23T04:13:23.547 Restoring packages.
2016-10-23T04:13:23.549 Starting NuGet restore
2016-10-23T04:13:23.549 Package restore failed:
2016-10-23T04:13:23.553 System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Azure.WebJobs.Script.Description.PackageManager.RestorePackagesAsync()
```

**Comment by fabiocav** [comment]
Glad to hear the 2nd issue was just a config problem, as I run that scenario frequently and haven't seen the issue.

The original issue has been addressed in the current runtime bits, so upgrading what the CLI is using will fix it.

**Comment by lindydonna** [comment]
@ahmelsayed Please close this issue when you update the current CLI
