### ISSUE TITLE
func new function produces error when global yo is installed

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-webjobs-sdk-script#854]
#### Repro steps

Provide the steps required to reproduce the problem

1. Install packages

```
npm install -g yo generator-azurefunctions azure-functions-cli
```

2. Create new function app and function

```
mkdir foo
cd foo
func init
func new function foofunc
```

#### Expected behavior

The function foofunc should be created.

#### Actual behavior

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\adrianha\AppData\Roaming\npm\node_modules\azure-functions-cli\node_modules\yo\lib\cl
i.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3


Tip: run `func run <functionName>` to run the function.
```

#### Known workarounds

Use `yo azurefunctions` instead of `func new function`

**Comment by adrianhall** [comment]
Note - lib/main.js#L13 contains the problem - it's the wrong way to embed Yeoman.  You should take a look at http://yeoman.io/authoring/integrating-yeoman.html

**Comment by jthake** [comment]
I can replicate this as tried to follow @adrianhall blog post too ;-)

**Comment by adrianhall** [comment]
Workaround: use `yo azurefunctions` to generate the function (instead of func new)

**Comment by jthake** [comment]
I get this error on doing that...
```
c:\Users\jthake\git\my-first-function-app>yo azurefunctions
C:\Users\jthake\AppData\Roaming\npm\node_modules\generator-azurefunctions\generators\app\index.js:21
const ALL_TEMPLATES = 'List all templates',
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as azurefunctions:app] (C:\Users\jthake\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\jthake\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\jthake\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:262:16)
```

**Comment by adrianhall** [comment]
@jthake This is a separate issue - probably related to your node version - Yeoman requires minimal version of node.  What version of node do you have installed?  (Tip: Upgrade to node 6.x LTS and try again).

**Comment by jthake** [comment]
ah yes, new machine, I was on v0.12.2. Is there no way the yeoman generator can have a dependency on versions of things to flag this?

**Comment by adrianhall** [comment]
It can, it doesn't, there is little we can do about it as it is not our product.

**Comment by lindydonna** [comment]
Will be handled by fix for https://github.com/Azure/azure-webjobs-sdk-script/issues/856, closing this issue as we're going to revisit the yeoman dependency.
