### ISSUE TITLE
"System.NullReferenceException" when creating a new "HttpGET(CRUD)-CSharp" function, via "func new"

### ISSUE THREAD

**Issue by DavidLudwig** [Azure/azure-webjobs-sdk-script#892]
When attempting to create a new Azure Function using "func new" and the "HttpGet(CRUD)-CSharp" template, errors are generated.

#### Repro steps

In a Windows Command Prompt window:

1. run: mkdir MyTestFunction
2. run: cd MyTestFunction
3. run: func init
4. run: func new
5. choose option, "List template by language"
6. choose option, "C#"
7. choose option, "HttpGET(CRUD)-CSharp"
8. enter name of function, minus quotes, "MyTestFunction"
9. run: func run MyTestFunction

#### Expected behavior

A local server starts up, and no errors are generated.

#### Actual behavior

A local server appears to start up in a new window, however errors are generated in this window:

```
Listening on http://localhost:7071
Hit CTRL-C to exit...
Debugger listening on [::]:63634
Error indexing method 'Functions.MyTestFunction'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.MyTestFunction' ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Host.Tables.TableAttributeBindingProvider.<TryCreateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Bindings.CompositeBindingProvider.<TryCreateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__0.MoveNext()
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Job host started
Job host stopped
Error indexing method 'Functions.MyTestFunction'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.MyTestFunction' ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Host.Tables.TableAttributeBindingProvider.<TryCreateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Bindings.CompositeBindingProvider.<TryCreateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__0.MoveNext()
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Job host started

```

Similarly, an error appears in the Command Prompt window that was used to execute, "func run MyTestFunction":

`Error: An error occurred while sending the request.`

#### Known workarounds

None, as yet known.

#### Related information 

This was reproduced with:
 * Windows 10 Pro, version 1607, build 14393.351
 * Node.js v6.9.1
 * Azure Functions CLI 0.1

If anyone could use more information on this, or re-attempts at reproduction, feel free to let me know.

**Comment by soninaren** [comment]
HttpGET(CRUD)-CSharp template requires Azure storage account in the output binding. Please follow the steps below to add the storage account to the function.json. 

1. Create a new storage account from Azure Portal. https://portal.azure.com (if you don't have a storage account already)
2. Run the following commands
   - `func login`
   - `func list storageaccounts`  (Verify that the newly created storage account shows up in the list)
   - `func set <storage account>` (from the previous command)
3. You should see a message like this `Secret saved locally in <storage accountname>_STORAGE`
4. Open function.json file from MyTestFunction
5. Update connection setting in the table binding to be 
    `"connection": "<storage accountname>_STORAGE",`
6. Execute using with `func run MyTestFunction`

**Comment by lindydonna** [comment]
Assigning to @ahmelsayed

**Comment by ashelley** [comment]
Hello, I see this is already being worked on but I was attempting to do a similar thing with the QueueTrigger-CSharpTemplate.  Using func run or func host I get an error 'Object not set to instance of object'.  I thought I would leave my reproduction steps here in case it helps someone.

```
$ func --version
Azure Functions Cli (1.0.0-beta.5)
Function Runtime Version: 1.0.0.0
```

```
$ func host start
Listening on http://localhost:7071/
Hit CTRL-C to exit...
Reading host configuration file 'C:\inetpub\wwwroot\azure-func-deploy-test\host.json'
Generating 1 job function(s)
Starting Host (HostId=ed667fc289ce4cd8a2c853510206b1ad, Version=1.0.0.0, ProcessId=28008, Debug=False)
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.MyQueueTrigger1'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
Error indexing method 'Functions.MyQueueTrigger1'
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Job host started
The following 1 functions are in error:
MyQueueTrigger1: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.MyQueueTrigger1'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
```

I am unable to follow the direction above using a 'set command' to set my storage account but i've modified my function.json manually.  Here are my steps to reproduce problem.  

1) in an empty directory run func init
```
$ func init
Writing .gitignore
Writing host.json
Writing appsettings.json
Initialized empty Git repository in C:/inetpub/wwwroot/azure-func-repro/.git/
```

2) create a new function from QueueTrigger-CSharp template

```
$ func new

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │   Welcome to the Azure   │
   `---------´   │   Functions generator!   │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Select an option... List all templates
There are 54 templates available
? Select from one of the available templates... QueueTrigger-CSharp
? Enter a name for your function... MyQueueTrigger1
Creating your function MyQueueTrigger1...
Location for your function...
C:\inetpub\wwwroot\azure-func-repro\MyQueueTrigger1


Tip: run `func run <functionName>` to run the function.
```

3) login to azure account

```
$ func azure login
```

(make sure proper subscription is active)

4) notice there is no way to connect function to azure storage account from cli (as stated above)

```
$ func azure storage
Usage: func azure storage <action> [-/--options]

Actions:
list  List all Storage Accounts in the selected Azure subscription
```

5) manually modify MyQueueTrigger1/function.json to set queueName and connection for proper storage account:

```
$ cat MyQueueTrigger1/function.json
﻿{
    "disabled": false,
    "bindings": [
        {
            "name": "myQueueItem",
            "type": "queueTrigger",
            "direction": "in",
            "queueName": "myrealqueuename",
            "connection":"myappsettingnameforstorageaccount_STORAGE"
        }
    ]
}
```

6) modify appsettings.json to include storage connection string

```
$ cat appsettings.json
{
        "myappsettingnameforstorageaccount_STORAGE": "DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=mykey"
}
```

7) attempt to start function host

```
$ func host start
Listening on http://localhost:7071/
Hit CTRL-C to exit...
Reading host configuration file 'C:\inetpub\wwwroot\azure-func-repro\host.json'
Generating 1 job function(s)
Starting Host (HostId=750ca3734b9145559f0db1212e1198dd, Version=1.0.0.0, ProcessId=32700, Debug=False)
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.MyQueueTrigger1'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
Error indexing method 'Functions.MyQueueTrigger1'
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Job host started
The following 1 functions are in error:
MyQueueTrigger1: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.MyQueueTrigger1'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
```

**Comment by ashelley** [comment]
possibly related.

https://github.com/Azure/azure-webjobs-sdk-script/issues/183

**Comment by lindydonna** [comment]
Yes @ashelley, and we're working on a fix to improve the error message. Note that you also need a value for "AzureWebJobsStorage"

Check out this blog post for more of a walkthrough: https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/

**Comment by lindydonna** [comment]
Closing as this is a documentation issue--you need to specify a value for the connection string.
