### ISSUE TITLE
[portal] Monitor output gives useless informations

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#899]
I'm using **Node.js** and on errors, when I'm going in Azure portal:

![image](https://cloud.githubusercontent.com/assets/4225430/20147615/18bd9bec-a6a9-11e6-935e-c9b4c536fe40.png)

And when I'm looking at output, it gives me quite useless informations:

![image](https://cloud.githubusercontent.com/assets/4225430/20147642/3ce5b356-a6a9-11e6-8dc6-8d54c4b57df0.png)

I'm logging my errors in Azure Function and I'm seeing my logs output via `logs` buttons:

![image](https://cloud.githubusercontent.com/assets/4225430/20147694/7614fdbc-a6a9-11e6-8be5-a99d11cf9e90.png)

Why not in `monitor`?

PS: Azure portal UX is messy.. really confusing (not talking about horizontal VS vertical scrolling.. )

-----

Output details:

```none
...obs.Script.Description.FunctionInvokerBase.<Invoke>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__3b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__1a.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by lindydonna** [comment]
We did a deployment recently that should have addressed this issue. Could you check to see if the issue is resolved?

**Comment by yvele** [comment]
@lindydonna I confirm it's much better 👍  

Thanks
