### ISSUE TITLE
Error in FunctionInvoker

### ISSUE THREAD

**Issue by markheath** [Azure/azure-webjobs-sdk-script#907]
I have a timer triggered C# function, which has been running successfully for a while but failed last night, but the logs don't seem to point to an issue with my own code. I manually ran it today and it worked fine. Here's the output from the failed invocation of the function:

````
...obs.Script.Description.FunctionInvokerBase.<Invoke>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__3b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__1a.MoveNext()
   --- End of inner exception stack trace ---
````

Any ideas what might cause this, or how I can debug further?

**Comment by fabiocav** [comment]
Would you mind sharing your function app (site) name either directly or indirectly (https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) so we can take a closer look?

**Comment by markheath** [comment]
Function app is called `markfunctionapp` - mostly being used for experiments.

**Comment by fabiocav** [comment]
@markheath , I took a closer look at the app and it does look like this was a function invocation exception due to an issue in the function logic (There was an IndexOutOfRangeException coming from the function).

Unfortunately, the stack was truncated above, so that information was mostly hidden from you. I'll follow up on this to make sure similar issues are surfaced in a clearer way.

**Comment by markheath** [comment]
ok that's great, thanks for looking into it

**Comment by fabiocav** [comment]
Adding @MikeStall here as he might have some information on how you can find more detailed logging information.

**Comment by markheath** [comment]
I'm guessing the full logs are in Azure Table storage, but would be great to see all the function output in the portal when you look at a failed invocation on the monitor tab. My function starts with a `log.Info` message so the fact I couldn't see that made me assume it hadn't got as far as running at all.

And BTW the bug was obvious once I knew it was an `IndexOutOfRangeException` - I had a `+1` instead of `-1`, so thanks again for helping me track down the problem.

**Comment by MikeStall** [comment]
Unfortunately, logging update is truncated in Functions. This is tracked by https://github.com/Azure/azure-webjobs-sdk/issues/863 . 

@markheath  - The latest Functions portal should show the exception Message property for failed instances. Do you see that? 
Alternatively, the SDK classic dashboard shows that information too.   You can get that at https://{YOUR_SITE_NAME}.scm.azurewebsites.net/azurejobs/#/functions

**Comment by markheath** [comment]
Is the latest functions portal the one at portal.azure.com? I can't see the exception Message on there (have just upgraded my function app to 0.9)

But the SDK classic dashboard is great! Didn't know that was available! A very handy summary.

**Comment by fabiocav** [comment]
I figured that as soon as you had the exception type, the fix would likely be pretty obvious :) That's why making sure that information is surfaced is so important.
