### ISSUE TITLE
InvalidOperationException: Assembly load context for function already exists.

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-webjobs-sdk-script#92]
Repro steps:

1. Create a new C# function with a queue trigger
2. Drop 50 messages into the queue
3. Watch the output

The following exception shows up multiple times in the logs:
```
2016-03-12T17:10:16 System.InvalidOperationException: Assembly load context for function 'cgillum-queue-csharp' already exists.
   at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoader.CreateContext(FunctionMetadata metadata, Assembly functionAssembly, FunctionMetadataResolver metadataResolver)
   at Microsoft.Azure.WebJobs.Script.Description.CSharpFunctionInvoker.GetFunctionTarget()
   at Microsoft.Azure.WebJobs.Script.Description.CSharpFunctionInvoker.<Invoke>d__21.MoveNext()
```
The function appears to eventually succeed dequeuing all the messages.

**Comment by davidebbo** [comment]
@fabiocav seems like some race condition in [CreateContext](https://github.com/Azure/azure-webjobs-sdk-script/blob/d15b3e3bb94382b1bfcb64daa08c9729ecd72510/src/WebJobs.Script/Description/CSharp/FunctionAssemblyLoader.cs#L53-L71). Is `FunctionAssemblyLoadContext` something that exists once per function and is used for all invocations (until the code changes)?

**Comment by fabiocav** [comment]
Yes, `FunctionAssemblyLoadContext`  is created once per function and lives until we re-emit and generate a new assembly for the function (which only happens on the invocation path). It does seem like we have a race condition there. I'll have that resolved and add a few tests to cover this. Thanks, @cgillum for the find and repro steps!

**Comment by davidebbo** [comment]
BTW, this easily repros with http functions as well, which is a bit easier to do. Just change the function code and fire 5 simultaneous http reqs to is.

**Comment by fabiocav** [comment]
I will have a fix for this later today.
