### ISSUE TITLE
CLI: New F# app fails to run locally

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Azure/azure-webjobs-sdk-script#970]
#### Repro steps

Provide the steps required to reproduce the problem

1. Install generator and CLI:

 `npm i -g generator-azurefunctions azurefunctions`

2. Create new F# project:

```
mkdir foo
cd foo
func init
func new (Pick HttpTrigger-FSharp)
```

3. Try to run function

`func run MyAzureFunction`

#### Expected behavior

Function runes without any problem

#### Actual behavior

Functions crashes we "nice" exception:

<details>
<summary>Stacktrace</summary>

```
Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '30dccf5b-ed00-4278-afd9-c62fe17a4021'
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.MyAzureFunction ---> Microsoft.CodeAnalysis.Scripting.CompilationErrorException: Script compilation failed. unknown(2,1): error FS1225: File 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.optdata' not found alongside FSharp.Coreunknown(2,1): error FS229: Error opening binary file 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.dll': File 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.optdata' not found alongside FSharp.Coreunknown(2,1): error FS3160: Problem reading assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Error opening binary file 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.dll': File 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.optdata' not found alongside FSharp.Coreunknown(2,1): error FS73: internal error: BuildFrameworkTcImports: no successful import of C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.dll
   at Microsoft.Azure.WebJobs.Script.Description.FSharpCompilation.EnsureAssemblyOption()
   at Microsoft.Azure.WebJobs.Script.Description.FSharpCompilation.GetEntryPointSignature(IFunctionEntryPointResolver entryPointResolver)
   at Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.<CreateFunctionTarget>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.<GetFunctionTargetAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.<InvokeCore>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.<Invoke>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__3a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__1a.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__1a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__2.MoveNext()
```

</details></br>

Most important part:
```
 FS1225: File 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.optdata' not found alongside FSharp.Coreunknown(2,1): error FS229: Error opening binary file 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.dll': File 'C:\Users\Krzysztof\AppData\Roaming\npm\node_modules\azurefunctions\bin\FSharp.Core.optdata' not found alongside FSharp.Core
```

#### Known workarounds

Copy `sigdata` and `optdata` manually from global system F# installation

**Comment by dsyme** [comment]
cc @sylvanc

**Comment by sylvanc** [comment]
I'm afraid I'm not familiar with the `azurefunctions` or `azure-functions-cli` projects.

@ahmelsayed , are you the maintainer of those projects? I ask because npm thinks you are the last one to publish them :) It looks like they need to include .optdata and .sig files for FSharp.Core.dll.

**Comment by Krzysztof-Cieslak** [comment]
Other solution would be creating by default project.json with FSharp.Core 4.4.0.0.... I think

**Comment by dsyme** [comment]
Anyone know where the source for the azure-functions-cli  project is?  A quick search didn't find it

**Comment by sylvanc** [comment]
I didn't find either `azurefunctions` or `azure-functions-cli`. The npm link points back here.

**Comment by Krzysztof-Cieslak** [comment]
I think there are on `cli` and `cli2` branches....

**Comment by lindydonna** [comment]
The CLI is on the rename-cli branch. The templates are in a separate location however: https://github.com/projectkudu/generator-azurefunctions

**Comment by fabiocav** [comment]
As @lindydonna mentioned, the CLI code is here: https://github.com/Azure/azure-webjobs-sdk-script/tree/rename-cli

We're just missing what was done with the runtime to include those files and make sure they're deployed.

**Comment by lindydonna** [comment]
Got it, it's not a templates issue. I think this issue in general will be address when we automate the CLI build: https://github.com/Azure/azure-webjobs-sdk-script/issues/877

**Comment by ahmelsayed** [comment]
Verified this is fixed by rebasing on latest dev. Closing.
